### ISSUE TITLE
Probleme avec protection par mot de passe

### ISSUE THREAD

**Issue by Th3ju** [FileZ/FileZ#100]
Bonjour,

L'upload de fichier avec un mot de passe fonctionne sans problème, par contre impossible de récupérer le fichier, cela me renvoie inévitablement "mot de passe incorrect".

Une idée ? 

Merci

Julien

**Comment by Th3ju** [comment]
Ok, je viens de trouver une piste : j'ai un virtualhost qui force a se connecter en https : 

<VirtualHost *:80>
 RedirectPermanent / https://FileZ.app.com
</VirtualHost>

Lorsque cette redirection est en place, impossible de telecharger le fichier.

Si je l’enlève, je peux télécharger en http et https avec le mot de passe sans problème.

Merci de votre aide

Julien

**Comment by almaghi** [comment]
de rien :)
