### ISSUE TITLE
Error: Internal Server Error Unknown table attribute "quota"

### ISSUE THREAD

**Issue by leewicked** [FileZ/FileZ#105]
Hi there,

i've installed FileZ with Database authentication, which works fine so far. But after I login, i only see an error, as you can see on the following image:

http://i46.tinypic.com/ab5nhz.jpg

Unfortunately I couldn't find any hints about this...hope you can help me out..thanks in advance!

**Comment by fannyny** [comment]
which version number do you have in your fz_info table ? Column "quota" have been added in the last migration (2.1.0-3). Do you have "filez-2.1.0-3" file in config db ? This file add quota column varchar

**Comment by leewicked** [comment]
Hi!

There is no "quota" column in my database, although i have filez-2.1.0-3.sql in my "config\db\migrations" folder.
Do i manually have to do this migration, or should it have been done with the installation?

I made a screenshot from my fz_info table:
http://i50.tinypic.com/20i8jsx.jpg

**Comment by fannyny** [comment]
When you lanch filez, the application checks if there are a difference between db_version variable and the value of db_version in fz_info table.
Check in your log folder if you have "migration needed" message.
Which value do you have for db_version in your fz_info table ?

**Comment by leewicked** [comment]
Hi!

I don't have anything in my fz_info table (please look at the last screenshot) - i think somethings messed up here.

Yes, the log files contains very often this phrase:

"[2012-06-21 19:30:23] [87.147.213.142]  Migration needed (db_version: ), executing the scripts..."

**Comment by fannyny** [comment]
ok, so try to add manually "filez-2.1.0-2.sql" in "db_version" in your table

**Comment by leewicked** [comment]
I tried adding filez-2.1.0-2.sql or filez-2.1.0-3.sql to fz_info, but unfortunately it did not solve the issue.

http://i45.tinypic.com/2zp742q.jpg

Can you take a screenshot of your fz_info or something like that?

**Comment by leewicked** [comment]
any other suggestions? please..i don't think, that it should be such a big problem, to fix that table, but i need to know, what values i have to add there.

**Comment by fannyny** [comment]
You can add directly into your user table column 'quota' with "varchar(60), latin1_swedish_ci, null: Non, default value: 2G"
and into your fz_info table "db_version = 2.1.0-4".
You can use your filez now ...

**Comment by leewicked** [comment]
Thanks, this error seems to be resolved. Now there's another one :(

"Could not determine temp directory, please specify a cache_dir manually"

**Comment by fannyny** [comment]
Do you have a /tmp directory ?

**Comment by leewicked** [comment]
Yes, I created one and also specified it in the first installation step.

**Comment by fannyny** [comment]
And do you have good rights on it ?

**Comment by leewicked** [comment]
Yep, I gave them all 777 for testing.

**Comment by fannyny** [comment]
Mmmhh ... thie error appears with :

```
    if ($this->_isGoodTmpDir('/tmp')) {
        return '/tmp';
    }
    if ($this->_isGoodTmpDir('\\temp')) {
        return '\\temp';
    }
    Zend_Cache::throwException('Could not determine temp directory, please specify a cache_dir manually');
```

And "isGoodTmpDir" method verify if the directory is readable and writable.
It's a very strange problem ...
