### ISSUE TITLE
Pb de connexion nouvel utilisateur

### ISSUE THREAD

**Issue by Jay64** [FileZ/FileZ#108]
Bonjour,

Je créée un nouvel utilisateur depuis la partie Administration, celui-ci se rajoute bien dans ma base mysql.
Par contre, impossible de me connecter avec le compte fraîchement créé, j'ai sans cesse "Nom d'utilisateur ou mot de passe incorrect".

Que se passe-t-il ? Je soupçonne le cryptage du mdp mais ne sais pas quoi vérifier pour trouver mon erreur ...

Merci !

Jérôme

**Comment by meilleurtiptop** [comment]
Bonjour,
Avez vous trouvé la solution je suis dans le même cas que vous actuellement.
