### ISSUE TITLE
Upload défaillant en GigaOctet

### ISSUE THREAD

**Issue by Siruv** [FileZ/FileZ#109]
Bonjour,

L'upload ne marche pas !
après avoir changé les valeurs dans .htaccess, rien n'y fait : la taille maximale du fichier à uploader est parfois juste, parfois fausse. 
Dès que l'on dépasse le gigaoctect pour le upload_max_filesize le fichier n'est pas mis sur le serveur.
Celui-ci a l'air de se transférer temporairement jusqu'à avoir une erreur fatale de dépassement de taille de fichier, alors que nous sommes en dessous.

Nous avons donc augmenté la taille dans des proportions délirantes du upload_max_filesize mais rien n'y fait.

Aucune erreur n'est visible dans les logs par contre la barre de progression affiche des valeurs négatives en allant de la droite vers la gauche.

Après modifications des valeurs dans le .htaccess nous avons fait la même chose dans le php.ini puis ensuite dans le vhost et enfin nous avons regardé si rien ne clochait du côté de httpd.conf et php.conf.

Je vous apporte d'autres précisions :

Nous sommes sous Centos 6 64 bits + Apache 2.2.15 + PHP 5.3.15 et la dernière version stable d'apc.

Autre précision le logiciel concurrent OpenUpload lui n'a aucun problème, je ne sais donc plus ou chercher.

J'ai déjà posté un commentaire sur le file de discussion suivant :

https://github.com/FileZ/FileZ/issues/96#issuecomment-6938111

Au final nous nous demandons si l'uplaod de plusieurs giga est possible avec FileZ.

Merci pour votre aide et vos réponses.

**Comment by ianbogda** [comment]
Je refait des tests dans la semaine, mais il me semble que ce que j'ai évoqué https://github.com/FileZ/FileZ/issues/96#issuecomment-7369885 résout le problème rencontré.

**Comment by ianbogda** [comment]
Avez vous essayer de nouveau ?
