### ISSUE TITLE
Ldaps FileZ Active Directory

### ISSUE THREAD

**Issue by ghost** [FileZ/FileZ#110]
Bonjour,

J'ai mis en place FileZ avec l'authentification AD (ldap). J'aimerai sécuriser la communication entre le serveur linux sur lequel tourne FileZ et le serveur Active Directory en utilisant le protocole Ldaps mais je n'y arrive pas.

Ce que j'ai fais:
- Modifier le fichier filez.ini (UseStartTls=true)
- Modifier le fichier /etc/ldap/ldap.conf (TLS_REQCERT =demand + TLS_CACERT= chemin du certificat où j'ai copier le CA AD)
- J'ai redémarrer Apache 

Mais j'ai une erreur.
Ai je oublié une étape?

Merci de votre aide

**Comment by ianbogda** [comment]
Bonjour,

avez vous résolu votre problème ?

si non pouvez vous poster les logs ?

cdlt,
