### ISSUE TITLE
Ordre de tri des utilisateurs dans le backoffice

### ISSUE THREAD

**Issue by Jay64** [FileZ/FileZ#111]
Bonjour,

Je voudrais changer l'ordre de tri des utilisateurs lorsque j'affiche la liste de tous les comptes existants.
Actuellement, ce tri est par ordre de création, et je voudrais un tri par Nom. Sur quel fichier dois-je agir pour changer ce réglage ?

Merci

Jérôme

**Comment by ianbogda** [comment]
Using Bach's tablesorter plugin: http://tablesorter.com

available also https://github.com/Mottie/tablesorter
