### ISSUE TITLE
Authentification hybride

### ISSUE THREAD

**Issue by ohmer1** [FileZ/FileZ#116]
J'aimerais pouvoir authentifier mes utilisateurs d'abord par LDAP (pour nos employés) puis ensuite sur une base de données locale lorsque le couple usager/pass ne passe pas la validation LDAP (pour nos usagers extérieurs comme un client ou un fournisseur). 

J'ai pas l'impression que ce soit possible en ce moment (c'est un bd locale ou LDAP, pas les deux), je me trompe?

**Comment by ianbogda** [comment]
Le plus simple serait de faire une nouvelle feuille pour vos usagers extérieurs puis pour cette feuille ainsi que pour celle de vos usagers internes.

ensuite utiliser `accountFilterFormat=”(&(objectClass=posixAccount)(uid=%s)(mailenable=true))”`  en changeant `mailenable=true` par une autre option de votre LDAP
