### ISSUE TITLE
Impossible de terminer l'installation

### ISSUE THREAD

**Issue by quotaatypique** [FileZ/FileZ#118]
J'ai installé FileZ sur mon serveur, mais impossible de le configurer : j'ai une suite de notices php « undefined index »… je suis perdue /o/

**Comment by ianbogda** [comment]
Bonjour,

cela fait quelques temps déjà, mais pourriez vous donner le détail de ces erreurs?

cordialement.

**Comment by ianbogda** [comment]
Veuillez essayer avec [la dernière version](https://github.com/FileZ/FileZ/archive/master.zip) qui est fonctionnelle.
