### ISSUE TITLE
ERROR 1005 (HY000): Can't create table 'filez.fz_file' (errno: 150)

### ISSUE THREAD

**Issue by kirkbrje** [FileZ/FileZ#120]
Hello,
it's impossible to create the foreign key in fz_file, please see below...
"ALTER TABLE `fz_file` ADD FOREIGN KEY (`created_by`) REFERENCES fz_user(id);"
=>ERROR 1005 (HY000): Can't create table 'filez.fz_file' (errno: 150)
(let me tell you that if I create fz_file without this foreign key, FileZ is OK but very slow - authentification through LDAP is OK).

Any ideas ?

mysql> SET NAMES 'utf8';
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE  `fz_info` (
    ->  `key`   VARCHAR( 30 ) NOT NULL ,
    ->  `value` VARCHAR( 50 ) NOT NULL ,
    ->   PRIMARY KEY (  `key` )
    -> ) DEFAULT CHARSET=utf8;
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO `fz_info` (`key`, `value`) VALUES ('cron_freq', NOW());
Query OK, 1 row affected (0.07 sec)

mysql> INSERT INTO `fz_info` (`key`, `value`) VALUES ('db_version', '2.1.0-2');
Query OK, 1 row affected (0.00 sec)

mysql> CREATE TABLE `fz_user` (
    ->   `id`          SERIAL      NOT NULL,
    ->   `username`    VARCHAR(30) NOT NULL,
    ->   `password`    VARCHAR(40) NOT NULL,
    ->   `salt`        VARCHAR(40),
    ->   `firstname`   VARCHAR(50) NOT NULL,
    ->   `lastname`    VARCHAR(50) NOT NULL,
    ->   `email`       VARCHAR(50) NOT NULL,
    ->   `is_admin`    BOOLEAN     DEFAULT 0,
    ->   `created_at`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
    -> ) ENGINE = MYISAM ;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE IF NOT EXISTS `fz_file` (
    ->   `id`              BIGINT UNSIGNED NOT NULL,
    ->   `del_notif_sent`  BOOLEAN         DEFAULT 0,
    ->   `file_name`       varchar(100)    NOT NULL,
    ->   `file_size`       INTEGER         DEFAULT 0,
    ->   `available_from`  DATE            NOT NULL,
    ->   `available_until` DATE            NOT NULL,
    ->   `comment`         varchar(200),
    ->   `download_count`  INTEGER         DEFAULT 0,
    ->   `notify_uploader` BOOLEAN         DEFAULT 0,
    ->   `created_by`      INTEGER         NOT NULL,
    ->   `created_at`      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ->   `extends_count`   INTEGER         DEFAULT 0,
    ->   `password`        varchar(40)     DEFAULT NULL,
    ->   INDEX       (`created_by`),
    ->   FOREIGN KEY (`created_by`) REFERENCES fz_user(id),
    ->   UNIQUE KEY `id` (`id`)
    -> ) DEFAULT CHARSET=utf8;
ERROR 1005 (HY000): Can't create table 'filez.fz_file' (errno: 150)
mysql>

**Comment by kirkbrje** [comment]
Bonjour,
problème "résolu", J'ai installé sans la contrainte Forign Key qui n'est pas super primordiable...

et bravo à l'équipe FileZ = beau produit !

**Comment by ianbogda** [comment]
#157
