### ISSUE TITLE
Pour mon info : cron

### ISSUE THREAD

**Issue by kirkbrje** [FileZ/FileZ#122]
Bonjour
quelqu'un pourrait-il expliquer comment fonctionne le "cron" de FileZ ?

En effet, pas d'inscription dans le crontab système et dans filez.ini on définit des variables cron...
Comment ça marche ?
Qu'est-ce qui tourne ?
Y-a-t-il un programme qui prend des ressources CPU en permanence ?
....

merci de vos éclaircissements !

**Comment by ianbogda** [comment]
Bonsoir,

Pour les cron, c'est une URL qui est interrogé par cron aux intervalles que vous définissez.

**Comment by ianbogda** [comment]
Bonjour,

des explications sont présnetes sur https://github.com/FileZ/FileZ/issues/132#issuecomment-12986084

**Comment by kirkbrje** [comment]
merci !
