### ISSUE TITLE
Authentification NTLM

### ISSUE THREAD

**Issue by gaelcalvar** [FileZ/FileZ#126]
Bonjour,

Nous avons réussi l'installation de FileZ avec authentification AD.

Est-ce que quelqu'un a déjà mis en place une authentification automatique avec le protocole NTLM ? Existe t-il un module pour FileZ ?

Merci d'avance

gael calvar

**Comment by Shawinkle** [comment]
Hello.

Je relance ce sujet car cela m'intéresse. :)
Actuellement, je suis connecté via AD. L'authentification NTML restant l'étape suivante...

Julien.

**Comment by thirion-isl** [comment]
Bonjour à tous

Pourriez vous nous faire part de votre fichier de configuration  filez.ini et surtout des paramètres concernant le ldap ?
pour ma part j'essai mais sans succès de connecter le serveur filez à mon ad.

Merci à vous tous

**Comment by gaelcalvar** [comment]
Voila mon fichier de conf : 

[user_factory_options]
baseDn = "DC=mon_domaine,DC=mon_dc,DC=fr"
host = "ldap://ip_de_mon_serveur_AD"
port = 389
bindRequiresDn = "false"
accountDomainName = "MON_DOMAINE"
username = "CN=MON_UTILISATEUR,OU=MON_SOUS_SOUS_OU,OU=MON_SOUS_OU,OU=MON_OU,DC=MON_DOMAINE,DC=MON_DC,DC=fr" ; mandatory
password = "mot de passe"  ; mandatory

[user_attributes_translation]
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "samaccountname"

**Comment by thirion-isl** [comment]
je viens de faire le test et ç a

**Comment by thirion-isl** [comment]
je viens de faire le test et ça ne marche toujours pas. si on part du principe que mon domaine est toto.local et que mon dc est dc.toto.local, est ce que le fichier te semble ok ? : 

baseDn = "DC=toto,DC=dc,DC=local"
host = "ldap://000.000.000.000"
port = 389
bindRequiresDn = "false"
accountDomainName = "toto"
username = "CN=filez,OU=ou-toto,DC=toto,DC=dc,DC=LOCAL"
password = "mdp"

faut il respecter majuscule / minuscule ?

EDIT : lorsqu'on se connecte, pour le nom d'utilisateur : 
toto\filez ou toto@toto.local ou simplement filez ?

**Comment by gaelcalvar** [comment]
Ca a l'air bon, mais essaie de te connecter a ton LDAP avec "ldap browser" (ou un truc du style)
Le domaine doit être en MAJUSCULE

le nom d'utilisateur doit être filez normalement.

**Comment by thirion-isl** [comment]
Hello

Merci pour les tuyaux, voici les paramètres renseignés pour que tout fonctionne :

[user_factory_options]
host = "ldap://XXX.XXX.XXX.XXX"
port = 389
username = "CN=filez,OU=OU-TOTO,DC=toto,DC=local"
password = "mdp"
bindRequiresDn = "false"
baseDn = "OU=OU-TOTO,DC=TOTO,DC=LOCAL"
accountDomainName = "TOTO"

Encore merci et à bientôt
