### ISSUE TITLE
Probleme d'URL dans les mails

### ISSUE THREAD

**Issue by gaelcalvar** [FileZ/FileZ#127]
Bonjour,

j'ai un problème d'url dans les mails.

dans l'interface web l'url est bien http://www.mondomaine.com/filez/id_fichier
dans les mails l'url est http://hostname/filez/id_fichier

J'aimerai que toutes les URL soit comme dans l'interface web.

Je précise que le serveur est sous debian 3.2.32-1

merci d'avance

**Comment by ianbogda** [comment]
Dans `config/filez.ini` veuillez utiliser 

```
[app]
force_fqdn = www.mondomaine.com
```

cela devrait suffire

**Comment by gaelcalvar** [comment]
Merci beaucoup, ça marche.
