### ISSUE TITLE
AD et compte administrateur

### ISSUE THREAD

**Issue by Flutiju** [FileZ/FileZ#128]
Bonjour,

Est-ce qu'il ai possible de définir un compte administrateur lorsque l'on utilise un Active Directory comme base utilisateurs ?
Merci.

**Comment by ianbogda** [comment]
Bonjour,

Comment verriez vous la chose?

**Comment by Flutiju** [comment]
Bonjour,

On pourrait, par exemple, définir un (ou plusieurs) utilisateur(s) de l'Active Directory comme administrateur(s), ça évite de gérer deux bases d'utilisateurs.

EDIT : On vérifiait je viens de m'apercevoir que la fonction existait déjà (le script add_admin.sh). J'étais passé à côté lors de l'installation... désolé.

**Comment by ianbogda** [comment]
effectivement :)
https://github.com/FileZ/FileZ/wiki/FAQ#how-to-add-an-admin-when-the-backend-used-is-ldap-
`scripts/add_admin.sh USERNAME`
