### ISSUE TITLE
Installation Filez (Unbutu server 12.10 + LDAP + Mysql)

### ISSUE THREAD

**Issue by sbafs** [FileZ/FileZ#132]
Bonjour,
J'essaye de mettre en place FileZ pour mon entreprise avec une authentification LDAP (j'ai un domaine Windows avec des contrôleur de domaine en 2008).
J'arrive à faire l'authentification mais après rien ne se passe ! Je reste sur la page de login !

filez.log :
[2013-01-21 08:46:25] [172.16.50.15]    Migration needed (db_version: 2.1.0-2), executing the scripts...
[2013-01-21 08:46:25] [172.16.50.15]    successful login of "xxxxxx@xxx.fr"
[2013-01-21 08:46:25] [172.16.50.15]    Migration needed (db_version: 2.1.0-2), executing the scripts...
[2013-01-21 08:46:25] [172.16.50.15]    Migration needed (db_version: 2.1.0-2), executing the scripts...

filez-error.log :
[2013-01-21 08:46:25] [172.16.50.15]    exception 'Exception' with message 'Unexisting database connection' in /var/www/filez/lib/Fz/Db.php:137
   Stack trace:
   #0 /var/www/filez/app/models/DbTable/Info.php(65): Fz_Db::getConnection()
   #1 /var/www/filez/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')
   #2 /var/www/filez/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()
   #3 /var/www/filez/app/views/layout/_footer.php(34): check_cron()
   #4 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #5 /var/www/filez/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)
   #6 /var/www/filez/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)
   #7 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #8 /var/www/filez/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)
   #9 [internal function]: render('<h 1>Page not fo...', 'layout/error.ht...')
   #10 /var/www/filez/lib/limonade.php(1450): call_user_func_array('render', Array)
   #11 /var/www/filez/lib/fz_limonade.php(73): html('<h 1>Page not fo...', 'layout/error.ht...')
   #12 /var/www/filez/lib/limonade.php(704): not_found(404, '(GET) /var/www/...', '/var/www/filez/...', 376)
   #13 /var/www/filez/lib/limonade.php(673): error_not_found_output(404, '(GET) /var/www/...', '/var/www/filez/...', 376)
   #14 [internal function]: error_default_handler(404, '(GET) /var/www/...', '/var/www/filez/...', 376)
   #15 /var/www/filez/lib/limonade.php(1808): call_user_func_array('error_default_h...', Array)
   #16 /var/www/filez/lib/limonade.php(647): call_if_exists('error_default_h...', 404, '(GET) /var/www/...', '/var/www/filez/...', 376)
   #17 /var/www/filez/lib/limonade.php(594): error_handler_dispatcher(404, '(GET) /var/www/...', NULL, NULL)
   #18 /var/www/filez/lib/limonade.php(376): halt(404, '(GET) /var/www/...')
   #19 /var/www/filez/lib/limonade.php(417): route_missing('GET', '/var/www/filez/...')
   #20 /var/www/filez/index.php(236): run()
   #21 {main}

J'avoue que suis un peux perdu pour la mise en place surtout la base de donnée

Par avance merci

**Comment by sbafs** [comment]
J'ai créé une base filez avec ça dedans :
SET NAMES 'utf8';
CREATE TABLE IF NOT EXISTS `fz_file` (
  `id`              BIGINT UNSIGNED NOT NULL,
  `del_notif_sent`  BOOLEAN         DEFAULT 0,
  `file_name`       varchar(100)    NOT NULL,
  `file_size`       INTEGER         DEFAULT 0,
  `available_from`  DATE            NOT NULL,
  `available_until` DATE            NOT NULL,
  `comment`         varchar(200),
  `download_count`  INTEGER         DEFAULT 0,
  `notify_uploader` BOOLEAN         DEFAULT 0,
  `created_by`      INTEGER         NOT NULL,
  `created_at`      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `extends_count`   INTEGER         DEFAULT '0',
  `password`        varchar(40)     DEFAULT NULL,
  INDEX       (`created_by`),
  UNIQUE KEY `id` (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE  `fz_info` (
 `key`   VARCHAR( 30 ) NOT NULL ,
 `value` VARCHAR( 50 ) NOT NULL ,
  PRIMARY KEY (  `key` )
) DEFAULT CHARSET=utf8;

CREATE TABLE `fz_user` (
  `id`          SERIAL      NOT NULL,
  `username`    VARCHAR(30) NOT NULL,
  `password`    VARCHAR(40) NOT NULL,
  `salt`        VARCHAR(40),
  `firstname`   VARCHAR(50) NOT NULL,
  `lastname`    VARCHAR(50) NOT NULL,
  `email`       VARCHAR(50) NOT NULL,
  `is_admin`    BOOLEAN     DEFAULT 0,
  `created_at`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = MYISAM ;

INSERT INTO `fz_info` (`key`, `value`) VALUES ('cron_freq', NOW());
INSERT INTO `fz_info` (`key`, `value`) VALUES ('db_version', '2.1.0-2');

**Comment by sbafs** [comment]
J'ai réussit à corriger des erreurs mais je n'arrive toujours pas à me connecter !
ci-joint les fichiers logs :

/var/log/filez/filez.log :
[2013-01-21 16:18:04] [172.16.50.15]    successful login of "xx@xx.fr"
[2013-01-21 16:18:37] [172.16.50.15]    successful login of "x.x@xx.fr"
[2013-01-21 16:22:22] [172.16.50.15]    successful login of "x@x.fr"
[2013-01-21 16:51:37] [172.16.50.15]    successful login of "x@x.fr"
[2013-01-21 16:55:47] [172.16.50.15]    successful login of "x@x.fr"

/var/log/filez/filez-error :
Je n'ai que les attributs LDAP qui remonte !

/var/log/apache2/filz-error.log :
[Mon Jan 21 16:55:47 2013] [error] [client 172.16.50.15] PHP Notice:  Undefined index: id in /var/www/filez/lib/Fz/Controller/Security/Abstract.php on line 84, referer: http://srv-upload/login

**Comment by sbafs** [comment]
C'est bon tout marche !

**Comment by ianbogda** [comment]
Bonjour,
pourriez-vous documenter votre réussite afin de partager votre expérience.

Par avance merci

**Comment by sbafs** [comment]
J'ai refait une installation propre a partir d'un serveur ubuntu 12.10
mis en place la version master, créé la base de donnée avec le script 
"SET NAMES 'utf8';
CREATE TABLE IF NOT EXISTS `fz_file` (
  `id`              BIGINT UNSIGNED NOT NULL,
  `del_notif_sent`  BOOLEAN         DEFAULT 0,
  `file_name`       varchar(100)    NOT NULL,
  `file_size`       INTEGER         DEFAULT 0,
  `available_from`  DATE            NOT NULL,
  `available_until` DATE            NOT NULL,
  `comment`         varchar(200),
  `download_count`  INTEGER         DEFAULT 0,
  `notify_uploader` BOOLEAN         DEFAULT 0,
  `created_by`      INTEGER         NOT NULL,
  `created_at`      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `extends_count`   INTEGER         DEFAULT '0',
  `password`        varchar(40)     DEFAULT NULL,
  INDEX       (`created_by`),
  UNIQUE KEY `id` (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE  `fz_info` (
 `key`   VARCHAR( 30 ) NOT NULL ,
 `value` VARCHAR( 50 ) NOT NULL ,
  PRIMARY KEY (  `key` )
) DEFAULT CHARSET=utf8;

CREATE TABLE `fz_user` (
  `id`          SERIAL      NOT NULL,
  `username`    VARCHAR(40) NOT NULL,
  `password`    VARCHAR(40) NOT NULL,
  `salt`        VARCHAR(40),
  `firstname`   VARCHAR(50) NOT NULL,
  `lastname`    VARCHAR(50) NOT NULL,
  `email`       VARCHAR(50) NOT NULL,
  `is_admin`    BOOLEAN     DEFAULT 0,
  `created_at`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = MYISAM ;

INSERT INTO `fz_info` (`key`, `value`) VALUES ('cron_freq', NOW());
INSERT INTO `fz_info` (`key`, `value`) VALUES ('db_version', '3.0-alpha') ON DUPLICATE KEY UPDATE value = '3.0-alpha';
"
Pour le fichier filez.ini :
J'avais des erreurs d'authentification LDAP car il ne faut pas mettre les majuscules !

[user_attributes_translation]
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "samaccountname"

Après tout cela je me suis connecté avec le future compte admin de Filez.
Et je suis allé lui appliqué la valeur 1 dans is_admin de la table fz_user pour avoir le backend !

Il me reste un soucis avec la tache cron qui ne se lance que si je vais me connecté sur l'interface d'administration.

Et j'ai encore ses message d'erreur dans filez-error.log :
[2013-01-28 17:41:35] [172.16.50.15]    exception 'Exception' with message 'Unexisting database connection' in /var/www/filez/lib/Fz/Db.php:139
   Stack trace:
   #0 /var/www/filez/app/models/DbTable/Info.php(65): Fz_Db::getConnection()
   #1 /var/www/filez/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')
   #2 /var/www/filez/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()
   #3 /var/www/filez/app/views/layout/_footer.php(30): check_cron()
   #4 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #5 /var/www/filez/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)
   #6 /var/www/filez/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)
   #7 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #8 /var/www/filez/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)
   #9 [internal function]: render('Page not fo...', 'layout/error.ht...')
   #10 /var/www/filez/lib/limonade.php(1450): call_user_func_array('render', Array)
   #11 /var/www/filez/lib/fz_limonade.php(73): html('Page not fo...', 'layout/error.ht...')
   #12 /var/www/filez/lib/limonade.php(704): not_found(404, '(GET) /ressourc...', '/var/www/filez/...', 376)
   #13 /var/www/filez/lib/limonade.php(673): error_not_found_output(404, '(GET) /ressourc...', '/var/www/filez/...', 376)
   #14 [internal function]: error_default_handler(404, '(GET) /ressourc...', '/var/www/filez/...', 376)
   #15 /var/www/filez/lib/limonade.php(1808): call_user_func_array('error_default_h...', Array)
   #16 /var/www/filez/lib/limonade.php(647): call_if_exists('error_default_h...', 404, '(GET) /ressourc...', '/var/www/filez/...', 376)
   #17 /var/www/filez/lib/limonade.php(594): error_handler_dispatcher(404, '(GET) /ressourc...', NULL, NULL)
   #18 /var/www/filez/lib/limonade.php(376): halt(404, '(GET) /ressourc...')
   #19 /var/www/filez/lib/limonade.php(417): route_missing('GET', '/ressources/jqu...')
   #20 /var/www/filez/index.php(222): run()
   #21 {main}

**Comment by fannyny** [comment]
Bonjour,

il vous manque la table 'cron_freq' qui permet de déterminer quand est-ce que la tache va se lancer.
mais je ne sais plus dans quelle branche se situe sa structure ...

**Comment by sbafs** [comment]
Bonjour et merci,

ce n'ai pas dans la table fz_info ?
j'ai ajouté :
INSERT INTO fz_info (key, value) VALUES ('cron_freq', NOW());

**Comment by fannyny** [comment]
Oui exact, il faut ajouter un premier enregistrement.
Il vous renvoit quand même toujours la même erreur ?

**Comment by sbafs** [comment]
Bonjour oui toujours la même erreur.

Pour la création de la tache cron j'ai procéder comme cela :
script : /usr/local/bin/filez-cron.sh
#!/bin/sh
#; -----------------------------------------------------------------------------
#; Cron job used to delete expired files.
#
#; This script needs to be executed by www user in order to append data to
#; existing log files.
#
#; IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#; Your CRON should execute a copy of this file in order to keep your 
#; configuration unchanged after filez updates.
#
#; -----------------------------------------------------------------------------

#; Directory where log file will be stored. Could be the same as in filez.ini
#; In this case, messages will be appended at the end of the file
LOG_DIR=/var/log/filez

#; Url of filez web root
URL=http://srv-upload:8080

LANG=fr

url_output="`wget --header=\"Accept-Language: $LANG\"  -q -O - $URL/admin/checkFiles`"

if test -n "$url_output"; then
    cd $LOG_DIR
    echo "[`date +'%FT%T%:z'`] [CRON] wget output: "$url_output >> "$LOG_DIR/filez-cron-error.log"
fi

Après j'ai lancé la commande :
crontab -e
j'ai mis :
0 11 \* \* \* su www-data -c "sh /usr/local/bin/filez-cron.sh" 2>/dev/null
et enregistré dans /usr/local/bin/crontab

Il me manque quelque chose ?

Merci

**Comment by sbafs** [comment]
De plus j'ai l'impression qu'il se lance seulement quand quelqu'un se connecte sur l'interface.
Contenu de la table fz_info :
mysql> select \* from fz_info;
+------------+---------------------+
| key        | value               |
+------------+---------------------+
| cron_freq  | 2013-01-30 16:25:56 |
| db_version | 3.0-alpha           |
+------------+---------------------+
2 rows in set (0.00 sec)

On voit bien que le script ne se lance pas à 11h comme prévu dans la tache cron

Si vous avez une idée car moi je sèche !
Cordialement

**Comment by ianbogda** [comment]
Bonjour,

Pour la gestion des cron:

voici ma configuration:

```
# m h  dom mon dow   command
00 23 * * * /repertoire/de/FileZ/scripts/cron.sh
```

de plus il faut que `cron.sh` soit executable (`chmod u+X cron.sh`)

Cdlt,
