### ISSUE TITLE
Installation de FileZ derrière un Proxy/reverse Proxy Web

### ISSUE THREAD

**Issue by Cdrik** [FileZ/FileZ#133]
Bonjour,

Je souhaite installer FileZ derrière un Proxy/reverse Proxy Web (sous Apache).
Comment prendre en compte celui-ci dans la config de FileZ ?
Je vous remercie.

Cordialement,
Cédric

**Comment by uhathanh** [comment]
Bonjour,

je fais passer filez à travers un proxy/reverse proxy Apache.
Pas de problème majeur en créant sur le serveur hébergeant l'application filez un virtualhost, puis configurer le proxy pointant vers ce virtualhost.
Le seul soucis est le mail généré pour le téléchargement du fichier: il indique le serveur hébergeant l'appli et non l'alias DNS qu'on veut donner.

il faut modifier le fichier app/models/File.php la ligne 
$name  = fz_config_get ('app', 'force_fqdn', "[l'alias choisi]");

A bientot

**Comment by ianbogda** [comment]
Il suffit de paramétrer `config/filez.ini`

```
[app]
…
force_fqdn = filez.domaine.fr
```
