### ISSUE TITLE
FileZ Configuration parameters for uploading 5Go files

### ISSUE THREAD

**Issue by cmarteau** [FileZ/FileZ#139]
hi,
I've set this configuration but i can't upload files more than 1 Go.

.htacccess
<IfModule mod_php5.c>
  php_value file_uploads On
  php_value upload_max_filesize 5G
  php_value post_max_size       5G
  php_value memory_limit        5G
  php_value max_input_time      18000
  php_value max_execution_time  18000
</IfModule>

apache :

<VirtualHost  xxx>
LimitRequestBody 0
</VirtualHost  xxx>

Does anyone has a valid configuration for uploading 5Go files ?

Thx

**Comment by cmarteau** [comment]
I can upload 2Go files with installing "mod-apreq2" and setting this in my virtualhost:
<VirtualHost xxxxxx>
        APREQ2_ReadLimit 4096M
        APREQ2_TempDir /data/filez/tmp
        LimitRequestBody 0
</VirtualHost>

But i can't upload more than 2 Go ...

**Comment by laureline** [comment]
And more than 2GB (5GB, for example) how we do?

**Comment by ianbogda** [comment]
```
<IfModule mod_rewrite.c>
  Options +FollowSymlinks
  Options +Indexes
  RewriteEngine on

  # RewriteBase /my_app/ # if your app is in a subfolder
  # RewriteBase /web/

  RewriteCond %{REQUEST_URI} !favicon.ico
  RewriteCond %{REQUEST_URI} !doc/user/(.*)\.
  RewriteCond %{REQUEST_URI} !resources/(.*)\.
  RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

<IfModule mod_php5.c>
  php_value file_uploads On
  php_value upload_max_filesize 1024m
  php_value post_max_size       1024m
  php_value max_input_time      900
  php_value max_execution_time  900
  php_value memory_limit 32M
  php_value suhosin.memory_limit 32M
</IfModule>
```

Note that if you use suhoshin do not forget to increase memory limit because php memory_limit is limited by suhoshin .
