### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by backpacker77** [FileZ/FileZ#145]
Bonjour à tous,

Je viens solliciter votre aide concernant l'installation de filez.

Je n'arrive vraiment pas à valider la page http://serveur_filez/configure
We found several errors while checking your configuration :
Can't connect to the database
could not find drive

En d'autre terme, je ne sais pas quoi mettre dans Filez Database (DSN, username, password)

Je vous remercie pour votre aide.

**Comment by BruceFeuillette** [comment]
Bonjour,

J'ai eu le même problème.
A priori il manque le paquet php5-mysql.
Lancer la commande
_dpkg --get-selections | grep php5-mysql_
Si rien n'est retourné, c'est que le paquet n'est pas présent, donc
_apt-get install php5-mysql_
Et le tour est joué :)

**Comment by ianbogda** [comment]
`````` mysql:host=localhost;dbname=filez```
*  host= le serveur où se trouve la base de données
*  dbname= le nom de la base de données pour FileZ

```Database username ``` = le nom de l'utilisateur de la base de données

```Database password``` le mot de passe de l'utilisateur pour accéder à la base de données.

Par exemple pour un filez sur 1and1 ou autre, ces 4 informations sont données à la créations de la base de données sur l'interface d'administration ou/et par mail.
``````
