### ISSUE TITLE
Probleme connection LDAP & AD 2003

### ISSUE THREAD

**Issue by xGanZx** [FileZ/FileZ#146]
Bonjour,

Je suis dans l'incompréhension !!! j'ai suivi toutes ces différentes Issue #128 et Issue #123 mais impossible de faire fonctionner la connections LDAP.

La seule chose qui diffère peut-être c'est que mes utilisateurs AD sont structurés dans différente OU représentant leur direction respective.
De plus j'utilise un Wordpress comme support intranet qui lui-même est connecté avec un plugin à mon AD pour l'authentification et ce dernier fonctionne parfaitement.

Du coup j'en perds mon latin et m'en remet à vous, si toute fois vous avez une procédure claire et détaillée sur le sujet.

Merci par avance aux éventuelles réponses.

**Comment by jean-phi** [comment]
Bonjour, avez-vous trouvé une solution, j'ai exactement le même problème.

**Comment by xGanZx** [comment]
Malheureusement NON ! J'ai l'impression qu'ils ont délaissé ce projet, plutôt prometteur, et que malheureusement ça ne fonctionne pas correctement.

Du coup j'ai opté pour une solution plus lourde, mais qui a le mérite de fonctionner en LDAP "Owncloud" mais je préférerai largement utiliser Filez !! Mais la procédure d'installation n'est pas complète, le LDAP ne fonctionne pas et le support est malheureusement un peu proche du Néant, mais comme ce sont des volontaires on ne va pas leur en vouloir :+1:

**Comment by jean-phi** [comment]
Merci pour cette réponse rapide.

J'ai réussi après un bon énervement en traversant le code.
J'avais le même contexte (Ad , utilisateurs déclarés dans plusieurs OU), un intranet connecté, des scripts php qui fonctionnaient.
Si vous changiez d'avis car beaucoup plus léger que owncloud (merci par ailleurs de l'avoir suggéré).

Dans le fichier de configuration filez.ini

[user_factory_options]
...
Remplacer:
username = cn=[user],ou=..,dc=domaine,dc=ext
Par
username = "[user]" ; le samaccountname de l'utilisateur de connexion uniquement.
...

**Comment by xGanZx** [comment]
Je vais remonter ce service et essayer ces différentes configurations, car comme vous je trouve owncloud plutôt lourd par rapport à un service comme Filez qui ce trouve être exactement ce que je recherche.

**Comment by xGanZx** [comment]
Bonjour jean-phi,
J'ai remonté filez et suis bloqué sur la config
![capture](https://f.cloud.github.com/assets/4425237/825019/91031768-f058-11e2-88be-9b2def4fa099.JPG)

Pourriez-vous m'aider donc à paramétrer cet espace correctement ?

**Comment by jean-phi** [comment]
Alors pour ma part, j'ai d'abord installé avec la BDD :

![19-07-2013 17-11-09](https://f.cloud.github.com/assets/5037527/826435/9d1a7c4e-f085-11e2-966e-5670a3b423ed.jpg)

Pour les user attributes mapping :
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "samaccountname"

Après j'ai joué avec le fichier de configuration filez.ini :

![19-07-2013 17-15-47](https://f.cloud.github.com/assets/5037527/826460/5427fe66-f086-11e2-9bc6-6d5dbc327398.jpg)

**Comment by xGanZx** [comment]
Salut Jean-Phi,

Alors j'ai suivi à la lettre ta méthode de configuration mais rien ne fonctionne ;)
Merci quand même de ton aide !!!

Jean

**Comment by ianbogda** [comment]
Bonjour,

Est-ce toujours le cas avec [la dernière version](https://github.com/FileZ/FileZ/archive/master.zip) ?

si oui, je remonte un serveur LDAP pour des tests et apporter une solution.

**Comment by xGanZx** [comment]
Pour vous dire franchement j'ai laissé tombé FIlez car je n'arrivait pas à faire fonctionner le LDAP :(

**Comment by Vincegive** [comment]
Bonjour,

Pour ma part, après avoir galéré quelques heures pour faire fonctionner Filez avec le LDAP (Active directory) : 
J'ai modifié le fichier de configuration filez.default.ini avec les paramètres LDAP proposé par JeanPhi 
J'ai utilisé filez 3.0 alpha

[user_factory_options]
baseDn = "DC=aaaa,DC=bbbb"
host = "j'ai mis l'adresse ip"
accountDomainName = "aaaa.bbbb"
username = "CN=nom_utilisateur,CN=Users,DC=aaaa,DC=bbbb"
password = "le_mot_de_passe"

[user_attributes_translation]
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "samaccountname"

**Comment by ianbogda** [comment]
Bonjour,

Pour la connexion entre FileZ et l'AD, je vous invite à suivre ce mode opératoire:
1. créer une Unité d'Organisation `FileZAccess`
2. y créer un groupe `FileZGroup`
3. Créer un utilisateur `FileZAdmin` qui sera dans le groupe `FileZGroup` **(il sera notre connecteur)**
4. Ajouter les membres que vous souhaitez dans ce groupe `FileZGroup`

Pour connaître la syntaxe pour connecter FileZ et votre AD, depuis le terminal windows de votre AD:

```
dsquery user
"CN=FileZAdmin,OU=FileZAccess,DC=aaaa,DC=bbbb"
```

Vous aurez la liste des membres du groupe `FileZGroup` depuis le terminal de votre AD:

```
dsquery * cn=FileZGroup,ou=FileZAccess,dc=aaaa,DC=bbbb -scope base -attr *
```

Au final, vous pourrez modifier votre configuration comme suit:

```
[user_factory_options]
baseDn = "DC=aaaa,DC=bbbb"
host = "IP.ADD.RE.SS"
accountDomainName = "aaaa.bbbb"
username = "CN=FileZAdmin,OU=FileZAccess,DC=aaaa,DC=bbbb"
password = "le_mot_de_passe_deFileZAdmin"
accountFilterFormat = "(&(&(objectClass=user)(sAMAccountName=%s))(memberOf=cn=FileZGroup,ou=FileZAccess,dc=aaaa.,dc=bbb))"

[user_attributes_translation]
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "samaccountname"
```

Cela devrait être bon et en plus vous n'aurez **QUE** les membres de `FileZGroup` dans FileZ.
