### ISSUE TITLE
Traduction de filez

### ISSUE THREAD

**Issue by aessers** [FileZ/FileZ#147]
Bonjour,

Nous utilisons votre application et nous sommes très content.

Par contre pourquoi certains textes ne sont pas traduits.

En fait dès qu'il y  des variables, cela ne fonctionne pas 

<?php echo __r('From %from% to %to%', array (

Le from reste from et to reste to par contre le echo simple fonctionne

?php echo __('Manage files')

Pouvez-vous m'expliquer ce que nous pouvons faire.

Merci par avance

**Comment by non092** [comment]
Bonjour,
J'ai exactement le même soucis.
Tu peut modifier le makefile i18n en remplaçant :

xgettext --keyword=__ --from-code=utf-8 --default-domain=$(DOMAIN) --output=$(DOMAIN).pot --files-from=./potfiles.txt ;

par 

xgettext --keyword=__ --keyword=__r --from-code=utf-8 --default-domain=$(DOMAIN) --output=$(DOMAIN).pot --files-from=./potfiles.txt ;

tu lance ensuite un "make update-po" et tu récupère le fichier .po pour la traduction française puis tu complète la traduction.

**Comment by srsr** [comment]
Bonjour,
Par manque de temps j'ai modifié ce qui n'était pas traduit 
manuellement. Je vous fournis mes textes et ou les modifications on été 
faites, ça porte essentiellement sur les messages envoyés par mail...

( les lignes modifiés sont précédés de "---->" )

modifier/ajouter les lignes suivantes du fichier /app/controlers/File.php :

```
 // Send mails
     $user = $this->getUser ();
     $mail = $this->createMail();
```

  ---->  $subject = __r('%sender% souhaite partager un fichier avec 
vous', array (
             'sender' => $user));
  ---->  $msg = __r('%sender% &agrave mis &agrave votre disposition le 
fichier "%file_name%". Il restera disponible du %available_from% au 
%available_until% &agrave l\' adresse :<br/><br/> <a 
href=%file_url%>%file_url%</a> <br/><br/> <EM>%msg%</EM>', array(
             'file_name' => $file->file_name,
             'file_url'  => $file->getDownloadUrl(),
             'msg'       => $_POST ['msg'],
             'sender'    => $user,
  ---->      'available_from'  => $file->getAvailableFrom()->toString  
(Zend_Date::DATE_LONG),
  ---->      'available_until' => $file->getAvailableUntil()->toString 
(Zend_Date::DATE_LONG),
         ));
  ---->  /*\* $mail->setBodyText ($msg);*/
  ---->  $mail->setBodyHtml ($msg);
         $mail->setSubject  ($subject);
         $mail->setReplyTo  ($user->email, $user);
         $mail->clearFrom();
         $mail->setFrom     ($user->email, $user);

modifier/ajouter les lignes suivantes du fichier /app/controlers/Upload.php:

```
  $user = $this->getUser ();
```

  ---->  $subject = __r('[FileZ] Transfert du fichier "%file_name%" 
rÃ©ussi',
             array('file_name' => $file->file_name));
  ---->  $msg = __r('Le fichier "%file_name%" est disponible du 
%available_from% au %available_until% &agrave l\' adresse suivante 
:<br/><br/> <a href=%file_url%>%file_url%</a><br/><br/>Votre fichier est 
t&eacutel&eacutechargable par votre interlocuteur en lui communiquant le 
lien ci-dessus.',
             array('file_name' => $file->file_name,
                   'available_from'  => 
$file->getAvailableFrom()->toString  (Zend_Date::DATE_LONG),
                   'available_until' => 
$file->getAvailableUntil()->toString (Zend_Date::DATE_LONG),
                   'file_url'  => $file->getDownloadUrl(),
                   'filez_url' => fz_url_for ('/', (fz_config_get 
('app', 'https') == 'always'))
             )
         );

```
     $mail = $this->createMail();
```

  ---->  /*\* $mail->setBodyText ($msg);*/
  ---->  $mail->setBodyHtml ($msg);
         $mail->setSubject  ($subject);
         $mail->addTo ($user->email, $user->firstname.' '.$user->lastname);

modifier/ajouter les lignes suivantes du fichier /app/controlers/Admin.php

  ---->      $subject = __r('[FileZ] Votre fichier "%file_name%" va 
bientÃ´t Ãªtre supprimÃ©', array (
                 'file_name' => $file->file_name));
  ---->      $msg = __r('Pour information votre fichier %file_name%, 
disponible Ã  l\'adresse %file_url% jusqu\'au %available_until%, va 
Ãªtre supprimÃ©.', array(
                 'file_name'       => $file->file_name,
                 'file_url'        => $file->getDownloadUrl(),
                 'filez_url'       => url_for('/'),
                 'available_until' => 
$file->getAvailableUntil()->toString (Zend_Date::DATE_FULL),
             ));
             $mail->setBodyText ($msg);
             $mail->setSubject  ($subject);
             $mail->addTo ($user->email);
             $mail->send ();

En espérant que cela puisse vous servir! ;)

---

**Comment by aessers** [comment]
Bonjour,

Merci pour ces infos, je vais tester.

Par contre j'ai vu qu'il y avait deux fichier .po et .mo.

Peux-t-on se servir de poedit avec ces 2 fichiers.

Merci

**Comment by non092** [comment]
Le fichier po c'est le fichier éditable et le .mo le fichier compilé une fois le fichier .po modifeir il faut le recompiler en .mo (j'ai utiliser poedit sur windows qui le fait automatiquement lors de l'enregistrement)

**Comment by aessers** [comment]
Ok pour toutes ces infos.

En fait j'ai bien modifier le fichier default.po en traduisant les morceaux qui ne l'étaient pas du dossier filez/i18n/fr/LC_MESSAGES

Puis je me suis mis dans le dossier /filez/i18n, j'ai modifié le Makefile avec vos instructions et j'ai lancé la commande make update-po et make mo

Cela fonctionne.

Merci

Comment peut-on contribuer à ce projet qui est très interessant. ?

**Comment by non092** [comment]
Il faudrait remonter l'info pour que cela soit corriger dans les prochaines versions mais je n'ai aps eu le temps de le faire ...

**Comment by pulsar895** [comment]
Laissez les gars je m'en occupe... au bout d'un an, je peux bien vous faire ça...
