### ISSUE TITLE
Internal Server Error : SQLSTATE[70100]: <<Unknown error>>: 1317 Query execution was interrupted

### ISSUE THREAD

**Issue by aeki** [FileZ/FileZ#149]
I run into the following error

exception 'PDOException' with message 'SQLSTATE[70100]: <>: 1317 Query execution was interrupted' in /homez.193/toto/FileZ/lib/Fz/Db.php:81
   Stack trace:
   #0 /homez.193/toto/FileZ/lib/Fz/Db.php(81): PDOStatement->execute(Array)
   #1 /homez.193/toto/FileZ/lib/Fz/Db/Schema.php(65): Fz_Db::findAssocBySQL('SELECT table_na...')
   #2 /homez.193/toto/FileZ/lib/Fz/Db/Schema.php(108): Fz_Db_Schema->getCurrentVersion()
   #3 /homez.193/toto/FileZ/index.php(138): Fz_Db_Schema->isOutdated()
   #4 [internal function]: before(Array)
   #5 /homez.193/toto/FileZ/lib/limonade.php(1808): call_user_func_array('before', Array)
   #6 /homez.193/toto/FileZ/lib/limonade.php(408): call_if_exists('before', Array)
   #7 /homez.193/toto/FileZ/index.php(223): run()
   #8 {main}

Could it be due to the fact that on my server the php value max_input_time is stuck to 60 (no right to modify php.ini here) ??

**Comment by ianbogda** [comment]
check https://github.com/FileZ/FileZ/issues/96#issuecomment-10182801
