### ISSUE TITLE
/filez/configure : not found

### ISSUE THREAD

**Issue by soumdematte** [FileZ/FileZ#153]
Bonjour,
Je viens d'installer un serveur ubuntu 12.04 LTS 64
J'ai suivi la doc d'installation suivante : http://blog.pablo-ruth.fr/index.php/filez-le-partage-de-fichier-auto-heberge/
et https://github.com/FileZ/FileZ

Quand j'ouvre la page http://localhost/filez, j'ai bien la 1ère page qui s'affiche mais quand je clique sur "continue" il me dit "not found"

j'ai pourtant suivi les pré-requis....

Une petite idée ?
sinon, existe t-il une distrib linux plus adaptée à FileZ ?

Merci

**Comment by Mickael-Martin** [comment]
Peux tu confirmer que tu as bien activer la ré-écriture des URL ?
Si tu connais un peu apache et php, teste ça avec un phpinfo.

**Comment by soumdematte** [comment]
Comment tu vois si j'ai activé la réécriture ?
sur mon dossier /var/www/filez/*, j'ai www-data:www-data en 755

j'ai fait un phpinfo, que veux tu voir ?

**Comment by Mickael-Martin** [comment]
tu dois avoir une ligne rewrite_url ou qq chose comme ça avec un booléen en face (activé ou pas).
Sinon tu peux faire ça avant de mettre Filez : http://www.webasyst.net/support/help/general-modrewrite-test.html

**Comment by soumdematte** [comment]
Je pige pas, j'ai répondu hier mais ma réponse n'apparait pas...
donc je disais que c'était une faute de frappe sur le nom du serveur dans le fichier de conf apache !!
tout marche à la perfection maintenant :)
Merci beaucoup de ton aide
