### ISSUE TITLE
Connexion AD impossible

### ISSUE THREAD

**Issue by soumdematte** [FileZ/FileZ#154]
Bonjour,

J'essaye de configurer mon AD 2008 mais je n'y arrive pas
J'ai suivi cette doc : https://github.com/FileZ/FileZ/issues/123
mais quand j'ouvre filez il me lance la page de conf...comme si le fichier filez.ini n'existait pas

une idée ?
Merci

**Comment by ianbogda** [comment]
veuillez essayer avec [la dernière version](https://github.com/FileZ/FileZ/archive/master.zip)

**Comment by ianbogda** [comment]
vous pouvez aussi jeter un œil sur https://github.com/FileZ/FileZ/issues/146#issuecomment-26128235
