### ISSUE TITLE
Can't connect to the ldap server Unknown Zend_Ldap option: db_use_global_conf

### ISSUE THREAD

**Issue by tomposmiko** [FileZ/FileZ#155]
After git clone I get this at installation time:

We found several errors while checking your configuration :

```
Can't connect to the ldap server
Unknown Zend_Ldap option: db_use_global_conf
```

If I comment that out in default.ini:

Can't connect to the ldap server
Unknown Zend_Ldap option: db_table

So install script doesn't work.

System is Ubuntu 12.04.

Thanks in advance,
tamas

**Comment by ianbogda** [comment]
Please try again with the last [master.zip](https://github.com/FileZ/FileZ/archive/master.zip).

**Comment by glasserre-pdw** [comment]
Hi.

I have the same problem with the last master.

Regards.
