### ISSUE TITLE
Base de donnée non crée à l'installation

### ISSUE THREAD

**Issue by Ujilon** [FileZ/FileZ#157]
Bonjour tout le monde,

Je viens de passer un petit moment à essayer d'installer FileZ, avec un succès tout relatif.
Premier problème remarqué, la base de donnée n'est pas crée (ou pas entièrement) après l'installation. Je suis certain que les identifiants sont corrects, car il y a deux tables, fz_file et fz_info qui apparaissent, mais vides. Rien cependant en relation avec fz_user que j'ai du créer et remplir à la main pour pouvoir me connecter.

Dès le début du process d'installation, le fichier de log d'erreur se remplit avec les lignes suivantes :

[Sun Sep 08 22:02:13 2013] [error] [client x.x.x.x] PHP Warning:  parse_ini_file(/var/www/.../web/config/filez.ini): failed to open stream: No such file or directory in /var/www/.../web/lib/fz_config.php on line 19

[Sun Sep 08 22:02:13 2013] [error] [client x.x.x.x] PHP Warning:  Missing or malformed config file. in /var/www/solaris/.../web/lib/fz_config.php on line 23

Je pense que c'est en partie a l'origine de tous les problèmes rencontrés par la suite.

Par la suite, une fois FileZ installé, un simple chargement de la page d'accueil fait apparaître la ligne d'erreur suivante :

[2013-09-08 22:18:53] [x.x.x.x]     exception 'Exception' with message 'Unexisting database connection' in /var/www/solaris/.../web/lib/Fz/Db.php:139

Et une vingtaine de lignes de la StackTrace qui vont avec.

Les permissions de tous les dossiers et fichiers sont celles par défaut, et l'user:group propriétaire est partout www-data

Est-ce que quelqu'un pourrait avoir l'amabilité de se pencher sur mon problème ? :)
Merci d'avance.

**Comment by ianbogda** [comment]
Bonsoir,

pour la partie:

> [Sun Sep 08 22:02:13 2013] [error] [client x.x.x.x] PHP Warning: parse_ini_file(/var/www/.../web/config/filez.ini): failed to open stream: No such file or directory in /var/www/.../web/lib/fz_config.php on line 19
> 
> [Sun Sep 08 22:02:13 2013] [error] [client x.x.x.x] PHP Warning: Missing or malformed config file. in /var/www/solaris/.../web/lib/fz_config.php on line 23

c'est normal, si le ficheir `config/filez.ini` n'existe pas.
pourle créer il faut copier `config/filez.ini.example`et le renommer `config/filez.ini`.

je regarde pour le reste.

**Comment by Ujilon** [comment]
Bonsoir,

Hélas, le fichier existe, et est bien à son emplacement...

23:08:07 - root :/var/www/solaris/.../web/config# ls -l filez.ini
-rw-r--r-- 1 www-data www-data 1248  8 sept. 22:14 filez.ini

Merci pour votre aide.

**Comment by ianbogda** [comment]
Pouvez-vous poster ce fichier `config/filez.ini` (en masquant les données sensibles) afin de voir si li n'y aurait pas un problème de typo à l'intérierur?
de plus quelle version PHP ?
quel OS ?
histoire de contextualiser le souci.
merci d'avance.

**Comment by Ujilon** [comment]
Here it is : http://pastebin.com/GbPBM8jB

PHP 5.3.3-7
Debian 6.0.7

**Comment by nawak86** [comment]
bonjour,

j'ai le même soucis.

++

**Comment by nawak86** [comment]
filez est quasiment abandonné en faite ?

**Comment by ianbogda** [comment]
Non, il vit toujours.

Mais les dev ont aussi un emploi à temps plein en plus du projet ;)

Je vais faire des tests dans la journée pour voir cela.

Cdlt.

Le 11 sept. 2013 à 03:08, nawak86 notifications@github.com a écrit :

filez est quasiment abandonné en faite ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/FileZ/FileZ/issues/157#issuecomment-24206569
.

**Comment by nawak86** [comment]
désolé c’était juste une question je cherche une solution pérenne.

pour information de mon côté : PHP Version 5.3.10-1ubuntu3.7
mysql  Ver 14.14 Distrib 5.5.32, for debian-linux-gnu (i686) using readline 6.2

Bonne journée

**Comment by nawak86** [comment]
Ujilon tu peux essayé de faire ta bdd toi même : 

-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1

## -- http://www.phpmyadmin.net

-- Client: localhost
-- Généré le : Dim 15 Septembre 2013 à 23:10
-- Version du serveur: 5.5.32
-- Version de PHP: 5.3.10-1ubuntu3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/_!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/_!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS _/;
/_!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION _/;
/_!40101 SET NAMES utf8 */;

## 

## -- Base de données: `filez`

---

## 

## -- Structure de la table `fz_file`

CREATE TABLE IF NOT EXISTS `fz_file` (
  `id` bigint(20) unsigned NOT NULL,
  `del_notif_sent` tinyint(1) DEFAULT '0',
  `file_name` varchar(100) NOT NULL,
  `file_size` int(11) DEFAULT '0',
  `available_from` date NOT NULL,
  `available_until` date NOT NULL,
  `comment` varchar(200) DEFAULT NULL,
  `download_count` int(11) DEFAULT '0',
  `notify_uploader` tinyint(1) DEFAULT '0',
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `extends_count` int(11) DEFAULT '0',
  `password` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`created_by`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

---

## 

## -- Structure de la table `fz_info`

CREATE TABLE IF NOT EXISTS `fz_info` (
  `key` varchar(30) NOT NULL,
  `value` varchar(50) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

## 

## -- Contenu de la table `fz_info`

INSERT INTO `fz_info` (`key`, `value`) VALUES
('cron_freq', '2013-09-15 21:56:30'),
('db_version', '3.0-alpha');

---

## 

## -- Structure de la table `fz_user`

CREATE TABLE IF NOT EXISTS `fz_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL,
  `password` varchar(40) NOT NULL,
  `salt` varchar(40) DEFAULT NULL,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `is_admin` tinyint(1) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quota` varchar(25) NOT NULL DEFAULT '2G',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

## 

## -- Contenu de la table `fz_user`

INSERT INTO `fz_user` (`id`, `username`, `password`, `salt`, `firstname`, `lastname`, `email`, `is_admin`, `created_at`, `quota`) VALUES
(1, 'admin', 'f41dbaba57981b28c187554edb35ee5de53436a9', NULL, 'FileZ', 'admin', 'foo@bar.com', 1, '2013-09-11 01:56:34', '2G'),

## 

## -- Contraintes pour les tables exportées

## 

## -- Contraintes pour la table `fz_file`

ALTER TABLE `fz_file`
  ADD CONSTRAINT `fz_file_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `fz_user` (`id`);

/_!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/_!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS _/;
/_!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by nawak86** [comment]
le seul problème que j'ai c'est les images qui ne s'affiche pas 
http://<URL>/filez/ressources/jquery.tablesorter/addons/pager/icons/prev.png

une idée ?

**Comment by Fredblue** [comment]
oui, il y a une typo ressources à la place de resources dans  app/views/user/index.php, cf issue #159

**Comment by nawak86** [comment]
merci j'ai corrigé le problème

par contre j'ai l'impression que le style css est pas pris en charge non ? le design ne ressemble pas à une installation que j'ai déjà vu.

![filez](https://f.cloud.github.com/assets/5274111/1146306/0ab8698e-1e56-11e3-935f-5645558ac325.jpg)

**Comment by nawak86** [comment]
![filez2](https://f.cloud.github.com/assets/5274111/1146350/7192fadc-1e58-11e3-9810-d0f1c943e50e.jpg)

ça n'a rien à voir avec le thème web 2.0 que je connais.
