### ISSUE TITLE
Authentification via un serveur LDAP Oracle failed

### ISSUE THREAD

**Issue by forum69** [FileZ/FileZ#16]
bonjour,

j'ai installé la dernière version. Installation sans problème sur une RHEL 5. Super travail.

Toutefois, impossible de m'authentifier sur un annuaire LDAP OID Oracle.

J'ai le message d'erreur suivant, mais ne suis pas certain qu'il soit relié à l'échec de l'authentification :

[2010-08-04 15:02:36] [192.168.1.86]    Error (Warning) strftime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /var/www/html/filez/lib/fz_log.php:39

[root@vana8715-6 ~]# date
mer aoû  4 08:52:56 CEST 2010

[root@vana8715-6 lib]# cat -n fz_log.php |grep 39
    39      $message = '['.strftime ('%F %T').'] '

Ce problème peut-il être la cause de l'"chec del'authrntification ?

merci,

lv

**Comment by forum69** [comment]
j'ai trouvé comment supprimé l'erreur : il faut ajouter dans le php.ini le cntenu suivant à la variable date.timezone :

[root@vana8715-6 httpd]# diff /etc/php.ini /etc/php.ini.2010.08.10 
946c946

## < date.timezone = "Europe/Berlin"

> ;date.timezone =
> [root@vana8715-6 httpd]#

par contre je continue à ne pas pouvir m'authentifier sur mon ldap oracle . Je continue à chercher.

**Comment by forum69** [comment]
mauvais copier/coller :

date.timezone = "Europe/Berlin"

**Comment by forum69** [comment]
Resolved. 
Here is how to configure filez.ini to authenticate against a LDAP ORACLE OIDDAS server  :

user_factory_options]
baseDn = "cn=Users,dc=domain,dc=fr"
host = "serveur.domain.fr"
useSsl = false
bindRequiresDn = true
username = "cn=p.nom,cn=Users,dc=domain,dc=fr"
password = "password"
accountFilterFormat = "(&(objectclass=*)(uid=%s))"

[user_attributes_translation]
firstname = "givenname"
lastname = "sn"
email = "mail"
id = "cn"

**Comment by ArnaudD** [comment]
Thanks for your contribution ! I've just updated the INSTALL file in the master branch.
