### ISSUE TITLE
reading permission on filez.ini

### ISSUE THREAD

**Issue by Thybo** [FileZ/FileZ#162]
Bonjour,
Le fichier filez.ini contenant des mots de passe en clair (smtp, base de donnée mysql), y a-t-il un moyen de le rendre non-lisible depuis le réseau sans jouer avec les Virtualhost ?

**Comment by ianbogda** [comment]
Dans le fichier `.htacces` rajoute:

```
<Files *.ini>
Order Deny,Allow
Deny from All
</Files>
```

**Comment by Thybo** [comment]
Je ne connaissais pas cette directive, merci !
