### ISSUE TITLE
modify max file size (at leat 9Go)

### ISSUE THREAD

**Issue by dglb** [FileZ/FileZ#179]
hi,

I change the configuration of FileZ (branch 2.0) to upload 9Go file.

I get this (french error) and negative pourcentage during upload for a 3Go file.

   Une erreur s'est produite pendant l'envoi du fichier. La taille du fichier dépasse la taille maximale.. : (20G)

Could you help me ?

my config is:

.htaccess:

  php_value upload_max_filesize 20G
  php_value post_max_size       25G

conf/filez.ini

user_quota = 15G

in database

fz_user.quota = 10G

**Comment by f0o** [comment]
I'm unsure if it's correlate but PHP has a 2G limitation for strings. if move_uploaded_file precaches the file as internal string this may be a reason why your 3G file is not being uploaded correctly.

Also I noticed that the hidden-input 'MAX_FILE_SIZE' causes all sorts of problems with different browsers, for compatibility reasons I had to remove that field from all forms. To check against this problem, enable debugging and check that the error-code is '2'.

Cheers,
f0o

//PS: I got no idea what that french stuff is but have you tried changing the language to english? or is the error hardcoded in french?
