### ISSUE TITLE
Page Blanche : problème avec la fonction getQuota

### ISSUE THREAD

**Issue by TomMilon** [FileZ/FileZ#209]
Bonjour,
Après avoir installé et configuré FileZ sur mon serveur, je me retrouve devant un page blanche.
J'utilise une connexion à une base de données mysql (v5.2.2) pour l'identification, formaté comme cela est expliqué dans la FAQ.
mon log php me donne le message suivant : 
[Wed Mar 04 15:49:08 2015] [error] PHP Fatal error:  Call to a member function getQuota() on a non-object in /home/fcbn/htdocs/filez/app/models/DbTable/File.php on line 187, referer: http://www.fcbn.fr/filez/configure
Je n'ai pas d'erreur particulière dans le log de filez

Vous auriez une idée d'où le problème pourrait-il venir?

NB : voici la fonction qui utilise cette ligne 187
    /**
     \* Return remaining disk space available for user $user
     *
     \* @param App_Model_User    $user   User data
     \* @return float            Size in bytes or string if $shorthand = true
     */
    public function getRemainingSpaceForUser ($user) {
        return ($this->shorthandSizeToBytes ($user->getQuota())
              - $this->getTotalDiskSpaceByUser ($user));
    }

**Comment by pierfu** [comment]
Bonjour,
l'appli ne peut pas contacter normalement ta DB.
Sur la page http://www.fcbn.fr/filez, j'obtiens cela : 
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'filez.fz_info' doesn't exist`
Il semble y avoir d'autres erreurs de configuration, par exemple, ton logo renvoie vers une page indisponible.
Attention aussi, ton php affiche les erreurs, il vaut mieux désactiver ça par la suite (display_errors = Off).
Il suffit généralement de bien suivre le README.mkd et de s'assurer que les permissions sont correctes et FileZ marche.

**Comment by Fredblue** [comment]
Et as-tu une colonne Quota dans la table fz_user ? mysql> show columns from fz_user; doit te donner la liste des colonnes.

**Comment by TomMilon** [comment]
Bonjour pierfu, bonjour Fredblue,

Merci pour vos conseils qui me font réaliser qu'il y a certainement un passage que j'ai dû rater.
J'ai déjà arrangé le logo c'est quand même mieux comme ça ^^.
Pour vous expliquer ma démarche, sachez que j'ai suivi en parallèle 2 tuto d'installation : celui disponible sur le github (aka le readme) et celui ci (http://www.it-connect.fr/partage-de-fichiers-avec-filez/).

Côté gestion des utilisateurs, je compte utiliser une simple base de données. Le 2ème tuto explique simplement comment créer cette base. Suite au message d'erreur et en cherchant un peu, j'ai cru comprendre que la configuration de fileZ pour se connecter à la base n'est pas si flexible que ça et impose notamment le nom des table (ici fz_user) et des champs.
J'ai donc paramétré la base en suivant les erreurs affichés.

-> Cependant, qu'est ce que c'est que cette fameuse table filez.fz_info? Elle n'est mentionnée nulle par dans les tutoriels d'installation? Est-elle censée être créée automatiquement lors de la configuration de fileZ?

-> Idem pour la colonne Quota? Je ne vois pas d'où elle vient et à quoi elle correspond? Elle doit être de type entier, texte, booléen...? En tout cas, effectivement, elle n'est pas présente dans ma table 'fz_user'

Merci pour vos réponse.

**Comment by TomMilon** [comment]
Up?

**Comment by TomMilon** [comment]
Je n'ai toujours pas trouvé de solution... Savez vous où je peux trouver un tuto concernant la construction de la base de données "user" de fileZ? Et qu'est ce que c'est que filez.fz_info?

**Comment by TomMilon** [comment]
Up

**Comment by TomMilon** [comment]
OK, désolé pour le dérangement.
J'ai tout simplement repris le code disponible dans https://github.com/FileZ/FileZ/blob/master/config/db/schema.sql et tout fonctionne comme sur des roulettes
