### ISSUE TITLE
Erreur LDAP : Unable to bind to server: Invalid DN syntax

### ISSUE THREAD

**Issue by cattouillart** [FileZ/FileZ#22]
Je n'arrivais pas à me connecter à Filez. Voici le message d'erreur dans "filez-error.log" :

Error (Warning) ldap_bind() [<a href='function.ldap-bind'>function.ldap-bind</a>]: Unable to bind to server: Invalid DN syntax in /var/www/html/internet/filez/lib/Zend/Ldap.php:849

Après lecture de la documentation Zend,
http://files.zend.com/help/Zend-Framework/zend.auth.adapter.ldap.html

j'ai ajouté une ligne au fichier "filez.ini" :
bindRequiresDn = "true"

Depuis ça fonctionne parfaitement.

**Comment by ArnaudD** [comment]
Bonjour, 
Ce détail est normalement décrit dans la doc et sur le formulaire d'installation

**Comment by cattouillart** [comment]
Effectivement je n'avais pas vu. Désolé pour le bruit.
