### ISSUE TITLE
PHP Fatal error:  Call to undefined function json_encode

### ISSUE THREAD

**Issue by forum69** [FileZ/FileZ#23]
bonjour,

Je suis en train d'installer filez sur un serveur de production après des tests.

je suis sur une Redhat RHEL 5.2
php 5.1.6
httpd 2.2.3

J'ai un problème d'affichage après l'authentification. Je perds en effet complètement la mise en page.
L 'affichage se fait sous une forme html brute. Cela reste fonctionnel, mais l'ergonomie et le visuel a complètement disparu.

J'ai l'erreur suivante dans les logs :

[Wed Sep 01 15:36:49 2010] [error] [client 192.168.1.86] PHP Notice:  Use of undefined constant E_RECOVERABLE_ERROR - assumed 'E_RECOVERABLE_ERROR' in /Apache/www/html/filez/lib/limonade.php on line 842, referer: http://filez.domain.fr/login
[Wed Sep 01 15:36:54 2010] [error] [client 192.168.1.86] PHP Fatal error:  Call to undefined function json_encode() in /Apache/www/html/filez/app/views/main/index.php on line 88, referer: http://filez.domain.fr/login

A noter que la mise en place de filez avec sur une plateforme de test et php 5.3.2 ne m'a pas posé de soucis.

Je peux difficilement upgrader le php sur le serveur actuel, qui est un serveur de prod avec pas mal d'applis web.

merci,

**Comment by forum69** [comment]
Je fais également la réponse, après avoir fouillé un peu plus sur le net.

ce lien décrit la méthode pour installer l'extension json au php 5.1.6 :

http://linuxchunks.com/2010/04/php-fatal-error-call-to-undefined-function-json_encode/

Cela marche  maintenant super bien.

lv.

A indiquer dans la FAQ.

**Comment by ArnaudD** [comment]
Merci pour l'info, je vais l'ajouter dans les docs
