### ISSUE TITLE
URL pour telecharger un fichier : FDQN   non positionné

### ISSUE THREAD

**Issue by forum69** [FileZ/FileZ#24]
bonjour,

Je suis confronté au problème suivant :

Dans ma config réseau, j'ai la recherche DNS suivante : domain.com.
Mon service filez est déclaré dans le DNS via filez.

Sur le LAN, si j'ouvre une session avec simplement http://filez, j'accède bien au site. L'URL générée est alors http://filez/eejf7E9.

SI ce lien est alors envoyé à un correspondant extérieur, il lui est alors impossible de récupérer le lien car la résolution DNS ne se fait pas, le nom de domain n'apparaissant pas.

Ou alors il y a un possible paramétrage dans le httpd.conf pour faire en sorte que lorsqu"on tape serveur, automatiquement l'url positionné dans le navigateur soit serveur.domain.com.

Il faudrait pouvoir fixer, dans le fichier filez.ini,  le FQDN ou l'URL permettant de récupérer le fichier à télécharger. On peut par exemple avoir un FDQN different entre le LAN et le WAN.

Pour l'instant, je ne peux donc ouvrir le service à l'extérieur.

merci,

**Comment by forum69** [comment]
j'ai cherché sans succès à utiliser les directives rewriterules sous apache.

Du coup, j'ai modifié le code du fichier File.php pour forcer le positionnement de l'URL avec le FQDN. Je n'ai pas vu d'anomalies dans l'utilisation.

cat -n File.php |grep url
ORIGIN :
   137          /*_return $url.'://'.$_SERVER["SERVER_NAME"].url_for ('/').$this->getHash ();_/

MODIFIED :
   138          return $url.'://'."filez.domaine.fr".url_for ('/').$this->getHash ();

**Comment by MaximeC** [comment]
Comment est la conf d'Apache ? filez est sur un vhost ?

**Comment by forum69** [comment]
J'utilise un virtual host. Voici le fichier de conf :

[root@domain0009 conf]# tail -3 httpd.conf

### INCLUDE filez transfert de fichiers

include /etc/httpd/conf/filez.conf

[root@domain0009 conf]# cat -n  filez.conf
     1  ### INSERTION POUR FILEZ
     2  
     3  <VirtualHost 192.168.112.138>
     4  #Alias /filez "/domain0009d11/Apache/www/html/filez"
     5      ServerAdmin root@localhost
     6      DocumentRoot /var/www/html/filez
     7  #   DocumentRoot /domain0009d11/Apache/www/html/filez
     8      ServerName filez.domain.fr
     9  
    10          ErrorLog  /var/log/httpd/filez-error.log
    11          CustomLog /var/log/httpd/filez-access.log combined
    12          LogLevel warn
    13  
    14  
    15          DirectoryIndex index.html index.php
    16  
    17          <Directory  "/var/www/html/filez">
    18      #    <Directory  "/domain0009d11/Apache/www/html/filez">
    19  
    20                  AllowOverride All
    21                  Options Indexes FollowSymLinks
    22                  order allow,deny
    23                  Allow from all
    24  
    25          #Options Indexes Multiviews
    26                  #AllowOverride None
    27                  #order allow,deny
    28                  #Options None
    29                  #AllowOverride Options FileInfo
    30  
    31  
    32                  # PHP tuning.
    33                  # Here you can tell for this _only_ specific VHost to allow big files and time to give file
    34                  # limit upload file to 750 MB
    35          php_admin_value post_max_size 750M
    36          php_admin_value upload_max_filesize 750M
    37                  # Allow 600 secondes of PHP execution to allow slow users to download file because PHP need to run 
    38                  # Be careful to not put high value here, 600 is should be enough and 300 could do the trick
    39                  # We are trying to find a better solution because here we are sensitive to DoS attack. If you have 
    40          php_admin_value max_execution_time 600
    41                  # Define a special directory for temporary files during the upload.
    42                  # PHP use by default /tmp. Tune this variable to fit your need.
    43                  # Remember, you should have enough space in your tmp/ partition to allow upload of your maximum fil
    44                  # Again, be careful, bad boys can try to fullfill your tmp partition!
    45          php_admin_value upload_tmp_dir "/var/tmp"
    46          </Directory>
    47  
    48  # Protect logfiles to be accessed by a web browser
    49  #        <Directory /var/www/html/filez/log>
    50  #                Options None
    51  #                AllowOverride None
    52  #                order deny,allow
    53  #                deny from all
    54  #        </Directory>
    55  
    56  
    57  </VirtualHost>

**Comment by ArnaudD** [comment]
J'ai ajouté un paramètre "force_fqdn" facultatif à mettre dans la section [app] de filez.ini
