### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by heutger** [FileZ/FileZ#26]
Hi,

a nice tool/idea, however I get many errors/problems and have a feature request:
1. Installation via aptitude does not work out on my Debian 5, I only have apt-get and it does not find any of the packages provided for progress bar.
2. After installation the requirements confuse, as they are already set (usually I expect a test script, which only shows, which requirement is not solved) also admin_value does not work inside .htaccess, only inside the confs of apache itself, inside .htaccess it must be without admin_.
3. Although the /tmp has been set, I still get errors always and anywhere, also if setting another tmp folder, it's required to change the lib/Zend/Cache/Backend/File.php manually to "detect" the tmp folder, this problem is a Zend Framework problem also reported on many other installations like Magento Commerce.
4. To have another user management like LDAP, ... is a great idea, however, if I just want to have the users managed by the app, there is everything missing, I need to work with MySQL directly, via phpMyAdmin or code sth. by myself to administer the users. That's one feature request.
5. Finally there seems not to be any rights check, as then the config file would be writeable.
6. Last issue after successfull go through all the top by manual handwork, I still get "an unknown error occured" if trying to upload a file. I first checked with a file near by the 700 MB, so it does not get any timeout, great, but it does also not allow to interrupt or finally store it, but I now also tried with really small files and as well, they did not store and I always got the same error.

Regards,
Christian

**Comment by ArnaudD** [comment]
Hi,
1. aptitude is now replaced apt-get
2. The installation process will be rethinked in filez 2.2. I will try to make this more clear. BTW, adminvalue in htaccess works when using `AllowOverride All` in your vhost - At least on our servers.
3. idem
4. Implemented in filez 2.1
5. filez 2.2
6. Did you resolved it since ?

Cheers
