### ISSUE TITLE
Limiter la taille des hash à 12 caractères max

### ISSUE THREAD

**Issue by ArnaudD** [FileZ/FileZ#28]
Pour éviter de dépasser la valeur max d'un attribut mysql BIGINT UNSIGNED.

**Comment by forum69** [comment]
bonjour,

Pour signaler que certains hashs ne comportent que 4 caractères dans les liens générés.  Est-ce normal ?
Cela peut paraitre peu, surtout pour certains utilisateurs.

**Comment by ArnaudD** [comment]
Bonjour,
Les hash sont générés aléatoirement selon une taille pouvant varier entre "min_hash_size" et "max_hash_size" (défini dans votre filez.ini).

**Comment by PiFa** [comment]
Bonjour,

Je ne sais pas si c'est un bug ou inehérent à mon installation, mais une valeur > 10 pour "min_hash_size" engendre systématiquement des erreurs:

Etape 1 : L'url est bien générée avec un hash > 10, mais en cliquant :

Etape 2 :  "Aucun fichier n'existe pour ce code"

Etape 3 : En retournant sur la page qui liste les fichiers uploadés, le hash a changé par rapport à l'étape 1...

Etape 4 : En cliquant à nouveau, plus d'erreur "pas de fichier pour ce code", mais une erreur purement Apache qui dit "Fichier Introuvable"

HTH,

**Comment by ArnaudD** [comment]
Bonjour, 
Je forcerai la limite de max_hash_size à 10 dans la prochaine version, je laisse le ticket ouvert en attendant.

**Comment by ArnaudD** [comment]
La valeur max est maintenant de 10.
