### ISSUE TITLE
Always SSL : problem with upload

### ISSUE THREAD

**Issue by PiFa** [FileZ/FileZ#30]
Hi,

With 
https = "always"

A strange problem appears : all seems ok, but uploading a file bigger than ~750Mo will stay stuck...

Multiples tries give me files stuck with different size, so i think there is a time-out somewhere in with SSL...

I try upgrade Apache setting SSLSessionCacheTimeout with no luck...

**Comment by MaximeC** [comment]
What about these PHP values?
        php_admin_value post_max_size xxxM
        php_admin_value upload_max_filesize xxxM
        php_admin_value max_execution_time xxx

**Comment by PiFa** [comment]
Here they are :

php_admin_value post_max_size 2000M
php_admin_value upload_max_filesize 2000M
php_admin_value max_execution_time 1200

They are the same for the https and non-https part...And, as i said, the temporary files haven't a fix size so i think it's not a size pb....
