### ISSUE TITLE
Retrouver un hash

### ISSUE THREAD

**Issue by PiFa** [FileZ/FileZ#34]
Bonjour,

Est-il possible de logguer les hash correspondants aux fichiers ? Je n'ai pas trouvé l'info...

Dans filez.log on trouve bien "Saved blablabla[247259242494140] uploaded by test@test.com"

Donc on a le nom du fichier, son id, la personne l'ayant uploadé, mais pas son hash !

Or pour retrouver qui a uploadé tel fichier correspondant à tel lien, on ne dispose que du hash....

**Comment by ArnaudD** [comment]
Une liste de tous les fichiers uploadés est désormais implémentée dans le backend qui devrait être disponible avec filez 2.1 (beta) d'ici la fin de la semaine prochaine.
