### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by spiorf** [FileZ/FileZ#35]
here is the default.po file for italian translation

**Comment by spiorf** [comment]
can't i attach files to issues???

**Comment by spiorf** [comment]
here it is :)

http://filez.spiorf.darktech.org/57207e

**Comment by ArnaudD** [comment]
Hi,

Thanks for your contribution, I will add it as soon as possible !

Bye

**Comment by ArnaudD** [comment]
Your translation is now in the repository, thanks again !
