### ISSUE TITLE
Automatic CRON

### ISSUE THREAD

**Issue by ArnaudD** [FileZ/FileZ#38]
Remove the need to configure a real CRON command. The CRON URL will be called from an HTML page, each X [hours|days]

**Comment by ArnaudD** [comment]
TODO : 
- Ajouter une variable dans filez.ini "cron_frequency" avec la [syntaxe php](http://fr2.php.net/manual/fr/datetime.formats.relative.php) afin d'utiliser strtotime ($cronFrequency, $lastCron) pour vérifier si le cron doit être fait.
- Si le cron doit être fait, ajouter à la fin du layout la balise <iframe src="$cronUrl" with="0px" height="0xp"></iframe>
- utiliser la table fz_info pour stocker le dernier CRON. Créer la classe App_Model_Table_Info dans le fichier app/models/Table/Info.php et y ajouter les fonctions getLastCronTimestamp et setLastCronTimestamp
- Vérifier que l'adresse de cron ne renvoi rien et que tout est loggué

**Comment by fannyny** [comment]
Feature ok.
For the moment, we must configure directly frequency of CRON in `file.iniè before the new FileZ version
