### ISSUE TITLE
Internal database auth

### ISSUE THREAD

**Issue by McFouch** [FileZ/FileZ#41]
Hi,

I want to use internal database auth to try Filez in a simple configuration but I can't find any clue in document how to use it.

I've ceated a user table in the filez database with username & password fields, added a user with sha1 password, so I pass the configuration step but can't login with this user...

Can you tell us more about this feature? or perhaps I've missed something somewhere! 

Thanks for your help.

regards,
Thierry

**Comment by ArnaudD** [comment]
Hi,

I've updated the FAQ with a question related to this : https://github.com/UAPV/FileZ/wiki/FAQ

I've not (re)tested it since a while ago, but it should work. Don't hesitate to update the wiki if you find an error.

Regards

**Comment by McFouch** [comment]
Hi Arnaud,

Thanks for your update. Works like I want now ;-)

Regards,
Thierry
