### ISSUE TITLE
config ignored if section doesn't exists in default config

### ISSUE THREAD

**Issue by sathieu** [FileZ/FileZ#46]
For example section auth_options.

Proposed patch:

<pre>
# git diff
diff --git a/lib/fz_config.php b/lib/fz_config.php
index 1724649..c53aac1 100644
--- a/lib/fz_config.php
+++ b/lib/fz_config.php
@@ -57,7 +57,7 @@ function merge_config ($user, $default) {
         $result [$section] = (array_key_exists ($section, $user) ?
             array_merge ($default[$section], $user[$section]) : $default[$section]);
     }
-    return $result;
+    return $result + array_diff_key ($user, $default);
 }
 
 /**
</pre>

**Comment by ArnaudD** [comment]
I fixed this [some time ago](https://github.com/UAPV/FileZ/commit/d7d183a0dd439a2a5168f76acb6a0f81ff736254) but forgot to merge it on the master branch, sorry. It's now fixed, thanks !
