### ISSUE TITLE
Refactor user management

### ISSUE THREAD

**Issue by ArnaudD** [FileZ/FileZ#47]
Filez 2.2 possèdera une table d'utilisateurs qui sera éventuellement synchronisée avec une source externe (LDAP, ou BD d'une application tierce).

**Comment by ArnaudD** [comment]
La table a été créée et le code a été réorganisé : https://github.com/UAPV/FileZ/commit/68d605e1a7cfe212bb27e778306c52c84d1b45a2

TODO : corriger [le script de migration](https://github.com/UAPV/FileZ/blob/backend/config/db/migrations/filez-2.2.0-1.sql) qui fait perdre les informations sur les utilisateurs des fichiers déjà uploadés.

**Comment by ArnaudD** [comment]
Le script de migration devrait maintenant être corrigé https://github.com/UAPV/FileZ/commit/c862cbc88c62e6fb320265101a94b8d67c0ad752

**Comment by ArnaudD** [comment]
TODO: lors de l'insertion du premier utilisateur en base, lui ajouter d'office les droits admins. A commenter...

**Comment by almaghi** [comment]
Ou insérer l'utilisateur "admin" lors de l'installation (donc demander un mot de passe lorsde l'install), comme wordpress.

**Comment by ArnaudD** [comment]
Oui ça me semble bien aussi

**Comment by almaghi** [comment]
l'utilisateur "admin" / "filez" est créé à l'installation.
