### ISSUE TITLE
Upload Max Size

### ISSUE THREAD

**Issue by Tiagans** [FileZ/FileZ#57]
Hi There!

I was trying to increase the upload max size up to 4GB (I've a server with 60GB) but when I change the .htaccess and try to login again says that Username and Password are not correct. When I put it back I can login.

Can you help me?

Thanks!

**Comment by ArnaudD** [comment]
Hi,

I can successfuly loging in when setting `php_value upload_max_filesize 4G`, `php_value post_max_size 4G` and `user_quota = "4G"`. 

Be aware that some browser have [limitations concerning uploaded file size](http://www.motobit.com/help/ScptUtl/pa33.htm)

Cheers

**Comment by Tiagans** [comment]
Hi ArnaudD, 

With php5 don't work, but I made an upgrade to php5.3 and it works now. I don't know why.

Thanks anyway. 

Cheers!

**Comment by eXoeXo** [comment]
Hello,

I have the exact same issue using php version: 5.2.6.dfsg.1-1+lenny13
max sizes of 1G are OK but with 2G+ login gets broken.
Is it a php version issue or is there something else?

Thank you
