### ISSUE TITLE
Fix: Share button doesn't work immediately after upload

### ISSUE THREAD

**Issue by steamraven** [FileZ/FileZ#63]
The share button of a newly uploaded file is created by ajax, but is missing event handler.  Until a reload, it is a link to /:filehash/share, which does not exist.

Fix
https://gist.github.com/1010452

Note:  The link is to /:filehash/share, but this route does not exist, and I don't see a controller function for it either.

**Comment by urbie-mk2** [comment]
This is a general issue that happens when the DOM is modified by AJAX after jquery binding took place (that happens after page has loaded). Read this: http://docs.jquery.com/FAQ#Why_do_my_events_stop_working_after_an_AJAX_request.3F

I am currently trying to fix it. might already work tomorrow.

**Comment by urbie-mk2** [comment]
This plugin takes care of all the event binding automatically:

http://docs.jquery.com/Plugins/livequery

**Comment by ArnaudD** [comment]
Hi,

Isn't it the same as the live function included in jquery ? http://api.jquery.com/live/

Sorry for not having replied to your other messages, I will but I'm quite busy currently.

Cheers

**Comment by urbie-mk2** [comment]
it does the same but in a different way, of course it's always better to use live(. main difference is that live() does use event bubbling, while livequery does not, it directly binds event handlers to the element.

**Comment by almaghi** [comment]
Thanks for your report and for your code! 
I was able to reproduce the bug unfortunately the proposed fix does not make it for me.
Does it resolve the bug for you?

I created the /:hash/share page as a workaround (see #86 fix). I think this is also useful for non-javascript users.
1d1ef0107a2e33a5d6e726e9e5b591ae128cbd5f fixed this issue at the moment. Comment and reopen this issue if you have some better code to fix this.

**Comment by alexdaums** [comment]
Hi,
On my test server I still have a problem.

After a transfer at the first click, I have this screen: http://cloud.seedaumas.fr/apps/files_sharing/get.php?token=3ebd7550e57ad3c48b88b147c9cda4da42d9ed3e&path=/Screenshots/Filez_1_share.png

And after I have this: http://cloud.seedaumas.fr/apps/files_sharing/get.php?token=3ebd7550e57ad3c48b88b147c9cda4da42d9ed3e&path=/Screenshots/Filez_2_share.png

**Comment by almaghi** [comment]
Hi Alex, thanks for your feedback.
What you've experienced is the current workaround behaviour, and the javascript still needs a fix.

Another workaround could be to reload the page after the upload event.
