### ISSUE TITLE
XSS hole security

### ISSUE THREAD

**Issue by lprat** [FileZ/FileZ#74]
EN: Whisked away to the main page allows the injection of an XSS in login fields. This field has no filter (the reloading of the page) and reloaded automatically if there is an authentication error allowing XSS.Thank you for your work.

FR: La page principale de filez permet l'injection d'un XSS dans le champs login. Ce champs n'a aucun filtre (dans le rechargement de la page) et il est rechargé automatiquement si il y a une erreur d'authentification permettant ainsi une faille XSS. Merci pour votre travail.

Cdlt Lionel

**Comment by almaghi** [comment]
Thank you Yann.
