### ISSUE TITLE
2.1 login new users problem

### ISSUE THREAD

**Issue by griff158** [FileZ/FileZ#76]
when upgraded to the 2.1 branche version i ran into a problem where i could login with a new user but couldn't upload any files or see the header with the correct username. When i changed the username to the same value as the id it all worked. after some searching i found the solution:

in / lib / Fz / Controller.php i change:

``` php
 self::$_user = Fz_Db::getTable('User')->findByUsername ($auth->getUserId ());
```

to

``` PHP
self::$_user = Fz_Db::getTable('User')->findById ($auth->getUserId ());
```

and added this new fucntion to FileZ / app / models / DbTable / User.php

``` PHP
public function findById($id) {
        $sql = 'SELECT * FROM '.$this->getTableName ().' WHERE id = ?';
        return $this->findOneBySQL ($sql, $id);
    }
```

**Comment by almaghi** [comment]
this is a config issue. Check your ini files:

```
[user_attributes_translation]
id        = username
```
