### ISSUE TITLE
db_use_global

### ISSUE THREAD

**Issue by romnvll** [FileZ/FileZ#79]
Hello,
i try to login into fileZ, but i have this error.

[2012-02-16 07:51:14] [192.168.14.24]   exception 'Zend_Ldap_Exception' with message 'Unknown Zend_Ldap option: db_use_global_conf' in /var/www/filez/lib/Zend/Ldap.php:318
   Stack trace:
   #0 /var/www/filez/lib/Zend/Ldap.php(132): Zend_Ldap->setOptions(Array)
   #1 /var/www/filez/lib/Fz/User/Factory/Ldap.php(43): Zend_Ldap->__construct(Array)
   #2 /var/www/filez/lib/Fz/User/Factory/Abstract.php(44): Fz_User_Factory_Ldap->_findByUsernameAndPassword('admin', 'filez')
   #3 /var/www/filez/lib/Fz/Controller/Security/Abstract.php(72): Fz_User_Factory_Abstract->findByUsernameAndPassword('admin', 'filez')
   #4 /var/www/filez/app/controllers/Auth.php(43): Fz_Controller_Security_Abstract->login('admin', 'filez')
   #5 [internal function]: App_Controller_Auth->loginAction()
   #6 /var/www/filez/lib/fz_limonade.php(31): call_user_func(Array)
   #7 [internal function]: fz_dispatcher('Auth', 'login')
   #8 /var/www/filez/lib/limonade.php(411): call_user_func_array('fz_dispatcher', Array)
   #9 /var/www/filez/index.php(235): run()
   #10 {main}
Aide

have an idea ???

Thank

**Comment by papangue** [comment]
You have configure the active directory or ldap integration.
Therefore removing the paramerter in the filez.default.ini section [user_factory_options] will fix the problem.

**Comment by romnvll** [comment]
thank i will try

**Comment by romnvll** [comment]
Thank, now i will try to configure with Active Directory
