### ISSUE TITLE
Errors: expects parameter 2 to be array 

### ISSUE THREAD

**Issue by setuplinux** [FileZ/FileZ#82]
I get the following error in my logs.  The application still seems to work but on every pageview I get 3 errors in the log that look something like this:

Error (Warning) in_array() expects parameter 2 to be array, string given in /var/www/filez/app/views/main/index.php:74

Looking through the code it goes to these 3 lines:

Line 71: <?php if (in_array ('email', $sharing_destinations)): ?>
Line 74: <?php if (in_array ('facebook', $sharing_destinations)): ?>
Line 77: <?php if (in_array ('twitter', $sharing_destinations)): ?>

**Comment by almaghi** [comment]
Hi, thanks for your report.
Fixed. Same issue than #85.
