### ISSUE TITLE
bug with sharing_destinations parameter (filez.ini)

### ISSUE THREAD

**Issue by HU-ET** [FileZ/FileZ#85]
under the section "[app]", the parameter sharing_destinations is defined as follow :

sharing_destinations[] = "email"
sharing_destinations = "Array"

it results an error with the $sharing_destinations php variable : it is a string with value "Array", not an array type with a cel with value "email"

you can see the error in logfile :
Error (Warning) in_array() expects parameter 2 to be array, string given in /var/www/filez/app/views/main/index.php

to correct the problem, write only this line :
sharing_destinations[] = "email"
in filez.ini

**Comment by almaghi** [comment]
fix: https://github.com/FileZ/FileZ/commit/a00639d2301beded62e5a0beb09367c6a2979457

thanks for your report. We are working on the master branch to release FileZ 3 asap.
