### ISSUE TITLE
Share file by mail do not work !

### ISSUE THREAD

**Issue by HU-ET** [FileZ/FileZ#87]
error message in app : "Page not found : (POST) /" + "Internal Server Error Unexisting database connection"
but DB is working well !

more details in logfile :
exception 'Exception' with message 'Unexisting database connection' in /var/www/filez/lib/Fz/Db.php:137
   Stack trace:
   #0 /var/www/filez/app/models/DbTable/Info.php(65): Fz_Db::getConnection()
   #1 /var/www/filez/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')
   #2 /var/www/filez/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()
   #3 /var/www/filez/app/views/layout/_footer.php(30): check_cron()
   #4 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #5 /var/www/filez/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)
   #6 /var/www/filez/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)
   #7 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')
   #8 /var/www/filez/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)
   #9 [internal function]: render('Page not fo...', 'layout/error.ht...')
   #10 /var/www/filez/lib/limonade.php(1450): call_user_func_array('render', Array)
   #11 /var/www/filez/lib/fz_limonade.php(73): html('Page not fo...', 'layout/error.ht...')
   #12 /var/www/filez/lib/limonade.php(704): not_found(404, '(POST) /', '/var/www/filez/...', 376)
   #13 /var/www/filez/lib/limonade.php(673): error_not_found_output(404, '(POST) /', '/var/www/filez/...', 376)
   #14 [internal function]: error_default_handler(404, '(POST) /', '/var/www/filez/...', 376)
   #15 /var/www/filez/lib/limonade.php(1808): call_user_func_array('error_default_h...', Array)
   #16 /var/www/filez/lib/limonade.php(647): call_if_exists('error_default_h...', 404, '(POST) /', '/var/www/filez/...', 376)
   #17 /var/www/filez/lib/limonade.php(594): error_handler_dispatcher(404, '(POST) /', NULL, NULL)
   #18 /var/www/filez/lib/limonade.php(376): halt(404, '(POST) /')
   #19 /var/www/filez/lib/limonade.php(417): route_missing('POST', '/')
   #20 /var/www/filez/index.php(235): run()
   #21 {main}

**Comment by almaghi** [comment]
fixed #80 with #58
