### ISSUE TITLE
Wrong icon for docx file

### ISSUE THREAD

**Issue by alexdaums** [FileZ/FileZ#88]
Here attached is an example on my test server

http://cloud.seedaumas.fr/apps/files_sharing/get.php?token=3ebd7550e57ad3c48b88b147c9cda4da42d9ed3e&path=/Screenshots/Filez_mauvais_docx.png

**Comment by almaghi** [comment]
thank you Alex for reporting this bug. It will be fixed :)

**Comment by psycofdj** [comment]
fixed.
actually, docx and other msword 2007 are zip files, i've added these common file extensions to force mimetype detection
