### ISSUE TITLE
Why go to the admin backend when i delete a file manualy

### ISSUE THREAD

**Issue by alexdaums** [FileZ/FileZ#89]
I noticed that as admin, when I delete a file manually, I am redirected to the admin backend.

I think it's strange, and I do not see why?

**Comment by almaghi** [comment]
You're right, this behaviour is strange, kind of a bug, let's change this.

**Comment by alexdaums** [comment]
Ok .. thank you very much for your great job!

**Comment by alexdaums** [comment]
Fix OK!

Thank You!
