### ISSUE TITLE
Password protect file

### ISSUE THREAD

**Issue by romnvll** [FileZ/FileZ#91]
Hello,
when we check "password" for protect file, no password is ask by filez ??

**Comment by almaghi** [comment]
I don't have this bug.
Is the password filed not shown when you check "Use a password"?! Could you look after javascript errors?

Notes:
- When I check "Use a password to download", the password field is shown and prompted (with a locker icon).
- Without Javascript, the password field is shown and used if "Use a password" is checked.
- If the password field is empty, the file will not be protected.
- You can always download the files you've uploaded but if you are not logged in, the password is required.

**Comment by romnvll** [comment]
I'm sorry, i was logged when i try the password ...
Thank you for your answer
