### ISSUE TITLE
ajout de nouveau type de fichier ?

### ISSUE THREAD

**Issue by chapy** [FileZ/FileZ#92]
Bonjour,

Bravo pour votre excellent logiciel, il est utilisé ici avec beaucoup d'intéret.
Je me demandais de quel facon était il possible d'ajouter de nouveau type de fichier qui ne semble pas connu de Filez.

ex: fichier   .EPS (vectoriel illustrator)
- Il faut avoir un .png de l'icone de représentation ?
- Nous devons changer quelque chose dans le code php (quel fichier) ?
- etc etc... ?

merci d'avance

Martin C.

**Comment by psycofdj** [comment]
Salut Martin,

Alors, les fichiers .eps (encapsulated postscript) sont déjà pris en compte par FileZ mais ils n'ont simplement pas d'image. 

Tu peux attribuer l’icône de ton choix en plaçant deux images nommées : application-postscript.png
dans les dossiers :
 resources/images/icons/mimetypes/32/
 resources/images/icons/mimetypes/48/

Chaque dossier contient les mêmes jeux d’icônes mais avec des tailles d'images différentes (respectivement 32x32 et 48x48 pixels). Les .eps déjà uploadés devraient instantanément apparaître avec la nouvelle icône.

**Comment by chapy** [comment]
merci, ca fonctionne parfaitement, je garde en note cette technique dans mon wiki internet pour documentation future !
