### ISSUE TITLE
Use of undefined constant FILE - assumed 'FILE' ...

### ISSUE THREAD

**Issue by schplurtz** [FileZ/FileZ#93]
hi.

Fresh install, and the first page gives this :

Notice: Use of undefined constant FILE - assumed 'FILE' in /home/www/filez/index.php on line 53 Notice: Use of undefined constant FILE - assumed 'FILE' in /home/www/filez/index.php on line 54 Notice: Use of undefined constant FILE - assumed 'FILE' in /home/www/filez/index.php on line 55 

I supposed that it should be FILE with 2 underscore on each side.

**Comment by Debayan101101** [comment]
Notice: Use of undefined constant _FILE_ - assumed '_FILE_' in C:\xampp\htdocs\SAMS\lib\student.php on line 2

Warning: include_once(C:\xampp\htdocs\SAMS/Database.php): failed to open stream: No such file or directory in C:\xampp\htdocs\SAMS\lib\student.php on line 3

Warning: include_once(): Failed opening 'C:\xampp\htdocs\SAMS/Database.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\SAMS\lib\student.php on line 3
