### ISSUE TITLE
Connection LDAP

### ISSUE THREAD

**Issue by christophe-lechenadec** [FileZ/FileZ#94]
Bonjour,
la connexion vers un LDAP Active Directory ne fonctionne pas.
j'ai l'erreur : Internal Server Error

Unknown Zend_Ldap option: db_use_global_conf

dans le fichier de Log d'erreur de fileZ j'ai  :
.
[2012-03-15 09:47:35] [10.1.17.67]      exception 'Zend_Ldap_Exception' with message 'Unknown Zend_Ldap option: db_use_global_conf' in /var/www/FileZ/lib/Zend/Ldap.php:318
   Stack trace:
   #0 /var/www/FileZ/lib/Zend/Ldap.php(132): Zend_Ldap->setOptions(Array)
   #1 /var/www/FileZ/lib/Fz/User/Factory/Ldap.php(43): Zend_Ldap->__construct(Array)
   #2 /var/www/FileZ/lib/Fz/User/Factory/Abstract.php(44): Fz_User_Factory_Ldap->_findByUsernameAndPassword('LECHENADEC-C', 'xxxxxx')
   #3 /var/www/FileZ/lib/Fz/Controller/Security/Abstract.php(72): Fz_User_Factory_Abstract->findByUsernameAndPassword('LECHENADEC-C', 'xxxxxx'')
   #4 /var/www/FileZ/app/controllers/Auth.php(43): Fz_Controller_Security_Abstract->login('LECHENADEC-C', 'xxxxxx')
   #5 [internal function]: App_Controller_Auth->loginAction()
   #6 /var/www/FileZ/lib/fz_limonade.php(31): call_user_func(Array)
   #7 [internal function]: fz_dispatcher('Auth', 'login')
   #8 /var/www/FileZ/lib/limonade.php(411): call_user_func_array('fz_dispatcher', Array)
   #9 /var/www/FileZ/index.php(222): run()
   #10 {main}

Ma config dans filez.ini :
[user_factory_options]
baseDn = "DC=CG56,DC=fr"
host = "cg56a.cg56.fr"
accountDomainName = "cg56.fr"
username = "CN=admin-task,OU=Administration,DC=cg56,DC=fr"
password = "xxxxxxx"

Cdt,

**Comment by romnvll** [comment]
j'ai eu le même probleme, ouvre ton fichier filez.defaut.ini et comment "db_use_global_conf"

**Comment by christophe-lechenadec** [comment]
Bonjour,

Merci pour la solution et la rapidité.
Cdt,

  www.morbihan.fr
Christophe LE CHENADEC
Technicien  – Service ingénierie et support
Direction des systèmes d’Information
Hôtel du département - 2 rue de Saint-Tropez - 56000 VANNES
tél : 02 97 54 58 21 - fax : 02 97 54 80 91 - courriel : christophe.lechenadec@cg56.fr 

-----Message d'origine-----
De : romnvll [mailto:reply@reply.github.com] 
Envoyé : jeudi 15 mars 2012 13:57
À : LE CHENADEC Christophe
Objet : Re: [FileZ] Connection LDAP (#94)

j'ai eu le même probleme, ouvre ton fichier filez.defaut.ini et comment "db_use_global_conf"

---

**Comment by gregpf81** [comment]
Bonjour,

Après avoir chercher de gauche à droite, je viens chercher de l'aide.
J'ai exactement de même message d'erreur (Internal Server Error -Unknown Zend_Ldap option: db_use_global_conf)

J'essaye de connecté mon serveur Filez à mon AD (Windows Server 2012R2) pour l'authentification utilisateurs).
Voici la config de mon fichier filez.ini :
[user_factory_options]
db_use_global_conf = "true"
db_table = "fz_user"
baseDn = "dc=adbdt,dc=local"
host = "192.168.0.2"
db_username_field = "username"
db_password_field = "password"
db_password_algorithm = "SHA1"

et celle de filez.default.ini :
[user_factory_options]
db_use_global_conf = "true"
db_table = "fz_user"
db_username_field = "username"
db_password_field = "password"
db_password_algorithm = "SHA1"

Auriez vous une idée ?
Merci
