### ISSUE TITLE
Image png Abimée

### ISSUE THREAD

**Issue by christophe-lechenadec** [FileZ/FileZ#95]
Bonjour,
j'ai un tout petit soucis d'affichage,
lorsque j'upload une Image ISO d'un CD
je n'ai pas le petit logo qui correspond.

en cherchant un peu il me semble que cela viendrait
du fichier
/resources/images/icons/mimetypes/48/application-octet-stream.png

Ce fichier est bien présent sur mon serveur, mais lorsque j'essaie de l'afficher
sur mon PC j'ai une erreur.

Le fichier est-il ok pour vous ?

Cdt,
Ch. Le Chenadec

**Comment by almaghi** [comment]
il faut définir l'extension .iso à https://github.com/FileZ/FileZ/blob/master/lib/limonade.php#L2164
Voir ensuite #92

**Comment by almaghi** [comment]
fixed by adf28984520c8c262b04fad0aab0919c27704092

**Comment by christophe-lechenadec** [comment]
Bonjour,

Effectivement il manquait 
La définition pour l'extension iso

Merci,
Cdt,

  www.morbihan.fr
Christophe LE CHENADEC
Technicien  – Service ingénierie et support
Direction des systèmes d’Information
Hôtel du département - 2 rue de Saint-Tropez - 56000 VANNES
tél : 02 97 54 58 21 - fax : 02 97 54 80 91 - courriel : christophe.lechenadec@cg56.fr 

-----Message d'origine-----
De : almaghi [mailto:reply@reply.github.com] 
Envoyé : mardi 20 mars 2012 00:19
À : LE CHENADEC Christophe
Objet : Re: [FileZ] Image png Abimée (#95)

fixed by adf28984520c8c262b04fad0aab0919c27704092#L0R2162

---
