### ISSUE TITLE
Upload gros fichier

### ISSUE THREAD

**Issue by christophe-lechenadec** [FileZ/FileZ#96]
Bonjour,

je n'arrive pas a uploder de gros fichier,
j'ai bien modifié le fichier .htaccess

```
<IfModule mod_php5.c>
  php_value file_uploads On
  php_value upload_max_filesize 4800M
  php_value post_max_size       4800M
  php_value max_input_time      1800
  php_value max_execution_time  1800
</IfModule>
```

cela ne change rien, lorsque j'essai par exemple de pousser un fichier de 800 Mo
il effectue presque tout le chargement du fichier, mais fini par afficher l'erreur :

Une erreur s'est produite pendant l'envoi du fichier. La taille du fichier dépasse la taille maximale.. : (4800M)

je n'ai pas de trace plus parlante de l'erreur qui se produit.

Cdt,
Ch. Le Chenadec.

**Comment by romnvll** [comment]
tu n'as pas accès à php.ini ?

**Comment by christophe-lechenadec** [comment]
Pour moi si, j'ai bien accès au fichier php.ini

J'ai essayé :
    De commenter le Bloc php dans le fichier .htacces
    Et de mettre toute les valeurs dans le php.ini
=> j'ai toujours le même problème

```
De Créer un fichier index.php
```

Contenant la commande phpinfo();
Lorsque je regarde toutes les infos j'ai bien
Les bonne valeurs   

Je ne vois d’où vient le blocage sur les Gros Fichiers.

Cdt,

Christophe LE CHENADEC

-----Message d'origine-----
De : romnvll [mailto:reply@reply.github.com] 
Envoyé : vendredi 16 mars 2012 20:00
À : LE CHENADEC Christophe
Objet : Re: [FileZ] Upload gros fichier (#96)

tu n'as pas accès à php.ini ?

---

**Comment by chapy** [comment]
Je viens aussi de découvrir que l'envoi de gros fichier (200megs) ne semble pas fonctionner.
Je vois rien dans les logs et le seul message à l'écran est: Une erreur inconnue est survenue pendant l'envoi du fichier

Ce ne me dit pas du tout ou chercher, si quelqu'un à une solution temporaire ou qu'un développeur peut regarder le problème, ce serait grandement apprécié.

bye bye

Martin C.

**Comment by chapy** [comment]
Bonjour Christophe,

Est-ce que tu as trouver une solution pour le problème d'envoie de gros fichier.

Je suis toujours incapable de téléverser des fichiers de plus de 150megs, nous aimerions vraiment pouvoir utiliser le logiciel pour les raisons qui nous ont poussés à le mettre en place. (échange de fichier volumineux avec des partenaires externes)

bye bye

Martin C.

**Comment by chapy** [comment]
Bonjour,

Après avoir chercher et chercher une solution du coté PHP, j'ai fait un test pour connecter sur le serveur directement.
Je dois vous dire que notre installation comporte un serveur mandataire inverse (Vulture) qui fait le travail d'un "proxy inverse". Donc en connectant directement sur le serveur (via une manipulation de mon fichier host) je peux téléverser des fichiers aussi gros que je veux, ca fonctionne bien.  Je vais donc avoir une conversation avec le gestionnaire du proxy inverse  :-)

bye

Martin C.

**Comment by christophe-lechenadec** [comment]
Bonjour,

Moi j'ai toujours mon Problème,
Malgré le changement des variables lié à PHP
Je ne peux pas Uploader au-delà de 750 Mo.

Je cherche Toujours....

Cdt,

  www.morbihan.fr
Christophe LE CHENADEC
Technicien  – Service ingénierie et support
Direction des systèmes d’Information
Hôtel du département - 2 rue de Saint-Tropez - 56000 VANNES
tél : 02 97 54 58 21 - fax : 02 97 54 80 91 - courriel : christophe.lechenadec@cg56.fr 

-----Message d'origine-----
De : Martin Chamberland [mailto:reply@reply.github.com] 
Envoyé : vendredi 23 mars 2012 17:08
À : LE CHENADEC Christophe
Objet : Re: [FileZ] Upload gros fichier (#96)

Bonjour,

Après avoir chercher et chercher une solution du coté PHP, j'ai fait un test pour connecter sur le serveur directement.
Je dois vous dire que notre installation comporte un serveur mandataire inverse (Vulture) qui fait le travail d'un "proxy inverse". Donc en connectant directement sur le serveur (via une manipulation de mon fichier host) je peux téléverser des fichiers aussi gros que je veux, ca fonctionne bien.  Je vais donc avoir une conversation avec le gestionnaire du proxy inverse  :-)

bye

Martin C.

---

**Comment by chapy** [comment]
Bonjour,

De notre coté, avec le retrait du Vulture (proxy inverse), notre problème est réglé.
Par contre, je dois t'avouer que je n'ai jamais tenter d'uploader un fichier qui dépasse 250megs, alors  :-(

De ce que je comprends tu tente d'uploader un fichier .ISO (dvd), avec la config du premier post 4800megs. (4.7gigs)
Je comprends pas pourquoi aucun développeur n'est intervenu dans le thread, normalement ils sont assez actifs ici.

bonne chance.

bye bye

Martin C.

**Comment by almaghi** [comment]
Je suis ennuyé car je n'arrive pas à reproduire ce bug. Sur mon environnement de développement local, je peux uploader et ensuite télécharger un fichier de 670Mo (voir http://bayimg.com/maNlBaADj).

Que disent les logs ? Pourrais-tu appliquer la config suivante  [app]debug=true et regarder de nouveau le debug-log ?

**Comment by chapy** [comment]
Je test ces parametres demain et vous reviens avec les resultats!

chapy from my SgS2
On Mar 27, 2012 3:35 PM, "almaghi" <
reply@reply.github.com>
wrote:

**Comment by christophe-lechenadec** [comment]
Bonjour,
Mes problèmes commence au-delà de 750 Mo,
Je mets en place le mode debug, je refais des tests
Et je vous tiens informé

Merci,

Cdt,

  www.morbihan.fr
Christophe LE CHENADEC
Technicien  – Service ingénierie et support
Direction des systèmes d’Information
Hôtel du département - 2 rue de Saint-Tropez - 56000 VANNES
tél : 02 97 54 58 21 - fax : 02 97 54 80 91 - courriel : christophe.lechenadec@cg56.fr 

-----Message d'origine-----
De : almaghi [mailto:reply@reply.github.com] 
Envoyé : mardi 27 mars 2012 21:35
À : LE CHENADEC Christophe
Objet : Re: [FileZ] Upload gros fichier (#96)

Je suis ennuyé car je n'arrive pas à reproduire ce bug. Sur mon environnement de développement local, je peux uploader et ensuite télécharger un fichier de 670Mo (voir http://bayimg.com/maNlBaADj).

Que disent les logs ? Pourrais-tu appliquer la config suivante  [app]debug=true et regarder de nouveau le debug-log ?

---

**Comment by chapy** [comment]
En fesant le débugage je m'apercois d'un truc:

Ceci est la section de mono fichier de config

```
[app]
use_url_rewriting = 1
log_dir = "/var/log/filez-dri"
upload_dir = "/var/www/filez-dri/uploads"
max_file_lifetime = 180
default_file_lifetime = 2
max_extend_count = 7
```

Ceci est la page web de la section "Administration"

```
app
debug = 1
send_us_a_file_feature =
use_url_rewriting = 1
log_dir = /var/log/filez
upload_dir = /var/filez/uploads
filez1_compat =
max_file_lifetime = 20
default_file_lifetime = 10
```

Certains parametres semble conforme, d'autre non. J'ai d'ailleur été obliger de créer un répertoire /var/log/filez pour éliminer un message d'erreur en mode DEBUG.

à voir...

Martin C.

**Comment by chapy** [comment]
Je viens de tenter un upload d'un fichier de 900megs, j'ai recu une erreur de taille maximal.
Lorsque je me connecte et clique sur le bouton envoyer un fichier, j'ai ce texte qui est inscrit juste au dessus de la boite de dialogue de l'envoie d'un fichier "Fichier (Taille maximale: 700M) :"

J'ai de plus changer le valeur dans mon fichier php.ini qui elle était de 750megs, j'ai changé pour 900megs. Je redémarre Apache et j'ai toujours la meme valeur lors de l'upload "Fichier (Taille maximale: 700M) :", normal ?

D'ou vient cette valeur de 700megs ??
Je vais chercher mais j'attends un aide d'un développeur.

merci

Martin C.

**Comment by chapy** [comment]
désolé, j'ai trouver mon problème.
La config que je cherchais est dans le fichier  .htaccess... désolé de cette mauvaise piste  :-(

bye

**Comment by chapy** [comment]
C'est vraiment pas ma journée, oublier mon post concernant les paramètres qui ne semble pas etre effectif.
C'est encore une fois mon erreur, j'ai ajouter une section additionelle [app] pour mettre la directive debug = true
Ce qui fesait en sorte de ne plus lire mon ancienne section [app] qui était juste au dessus.

désolé encore...  :-)

Martin C.

**Comment by fannyny** [comment]
Bonjour,

pour ceux qui ont encore le problème sur les gros fichiers qui ne s'uploadent pas malgré le changement du php.ini ou du .htacess, sachez que le mod_php5.c du htaccess a une taille limite d'upload pour les fichiers, et ceci quelque soit la valeur indiquée dans le php.ini.
Si vous avez la dernière version du module, vous pouvez ajouter une option afin de signaler l'action à faire si la taille limite est dépassée.

**Comment by Siruv** [comment]
Bonjour,

j'ai lu tout le post et malheureusement je n'ai pas trouvé de solution à mon problème.

En effet au delà de 900Mo, je pense dès que je passe la barre du Go; j'ai le même problème que vous tous.

J'ai donc modifié le htaccess, le php.ini le httpd.conf.

Mais rien n'y fait!

Cela devient déroutant, je suis sous Centos 6 en 64 bits, tous les prérequis de l'installation sont bien validés.

Si quelqu'un a une idée je suis preneur car c'est vraiment embêtant.

Cordialement.

**Comment by ianbogda** [comment]
Bonjour,

Verser un fichier volumineux via http demande de la mémoire.
Dans `.htaccess` tenter :

```
php_value memory_limit=32M
```

De plus, il est préférable de mettre la valeur du fichier en Mo :

```
php_value post_max_size=1024m
php_value max_execution_time=900
php_value max_input_time=900
```

**Comment by ianbogda** [comment]
Bonjour,

Je suis sur une piste complémentaire : la durée de vie de session.
Je me penche la dessus la semaine prochaine.

Cdlt,
Piste : http://www.php.net/manual/fr/features.file-upload.php#78017

**Comment by kirkbrje** [comment]
Bonjour,
pour info j'ai réussi à uploader un fichier de 1Go (fichier généré avec commande linux "dd if=/dev/zero of=monfic1Go count=1 bs=1024M".

Ma configuration (1030M pour mettre un peu plus que 1024)

```
.htaccess
  php_value file_uploads On
  php_value upload_max_filesize 1030M
  php_value post_max_size       1030M
  php_value max_input_time      1200
  php_value max_execution_time  1200
```

```
php.ini
post_max_size = 1030M
upload_max_filesize = 1030M
max_execution_time = 1200
```

httpd.conf

```
<VirtualHost xxxxxxxxxxxxxxx>
        ServerName xxxxxxxxxxxxxxx
        DocumentRoot /var/www/html/FileZ/files
        ErrorLog /var/log/filez-error.log
        CustomLog /var/log/filez-access.log combined
        LogLevel warn
        RewriteEngine on
        <Directory /var/www/html/FileZ/files">
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>
        php_admin_value upload_max_filesize 1030M
        php_admin_value post_max_size 1030M
        php_admin_value max_execution_time 1200
        php_admin_value upload_tmp_dir "/media/data/tmp"
</VirtualHost>
```
