### ISSUE TITLE
Upload Progress?!?

### ISSUE THREAD

**Issue by JaG-v2** [FileZ/FileZ#99]
Bonjour et merci pour cette contrib...
Seul PB le suivi de l'upload ne fonctionne pas.
J'ai bien installé APC et uploadprogress, mais rien n'y change.
En uppant, j'ai une erreur : 
upload starts...
GET http://www.xxxx.com/upload/progress/4f70a65c66227
"NetworkError: 404 Not Found - http://www.xxxx.com/upload/progress/4f70a65c66227"
Check Progress Error...
Upload progress not found.
En regardant le code source, je vois progressUrl:  '<?php echo url_for ('upload/progress/') ?>'
Bien évidemment il n'y a pas de rep upload ou progress.
Je tourne sur Win 2k8 R2, j'ai testé sous IIS et Apache via Wamp et c'est le même résultat
Merci pour l'aide

**Comment by almaghi** [comment]
upload/progress/:id est bien défini dans index.php:

```
fz_dispatch_get  ('/upload/progress/:upload_id' ,'Upload'      ,'getProgress');
```

Le bug est donc dans la fonction getProgressAction d' Upload.php controller.
Merci pour ton rapport.

**Comment by JaG-v2** [comment]
J'ai regardé getProgressAction et 
$progress = $progressMonitor->getProgress ($uploadId); retourne une variable vide.
J'ai donc fait un apc_exists('upload_'.$uploadId); et ça retourne false

**Comment by kirkbrje** [comment]
Bonjour,
il y a un correctif ?

que veut dire [ J'ai donc fait un apc_exists('upload_'.$uploadId); et ça retourne false]
=> faut-il ajouter apc_exists('upload_'.$uploadId);  ? dans quel fichier et où ?

**Comment by jicehix** [comment]
Bonjour,

Je rencontre le même problème. Avez-vous trouvé une solution ?

Cordialement,

**Comment by kirkbrje** [comment]
Non, j'y ai renoncé.
J'utilise le logiciel sans cette fonctionnalité.

**Comment by jicehix** [comment]
Ok, merci pour la réponse, je vais me pencher un peu plus sérieusement sur le sujet.

L'absence de progress bar n'est pas si problématique depuis notre campus, par contre les usagers en ADSL depuis chez eux ont du mal à s'assurer que l'upload est bien en cours... :/

**Comment by HornWilly** [comment]
Bonjour,

J'ai eu le même bug. 
$progressMonitor->getProgress ($uploadId); retourner null

J'ai trouvé le probléme sur CentOS 5 qui vient de ModSecurity.

Voici la solution mais elle désactive une sécurité sur votre serveur :
vi /etc/httpd/conf.d/modsecurity.conf
Rechercher SecRequestBodyAccess On
Remplacer par SecRequestBodyAccess Off

Bien à vous,

**Comment by jicehix** [comment]
Bonjour,

Malheureusement ce ne semble pas être ça qui pose problème, dans mon cas du moins. Mod_security n'est pas installé par défaut sur les Debian, il n'y a donc rien à désactiver de ce côté-là... Pas de SElinux ou suhoshin non plus qui pourraient perturber le fonctionnement d'uploadprogress... :(

Merci en tout cas pour votre réponse !

Cordialement,

**Comment by jicehix** [comment]
J'ai enfin réussi à faire fonctionner cette satanée barre de progression, sur une Debian Wheezy : 
- apt-get install libapache2-mod-php5
- pecl uninstall uploadprogress
- installation manuelle d'uploadpgrogress à partir du dernier package source : http://pecl.php.net/package/uploadprogress (la routine : configure && make && make install) 
- ajout de la directive apc.rfc1867 = 1 dans /etc/php5/conf.d/apc.ini
- progress_monitor = "Fz_UploadMonitor_ProgressUpload" <- dans le fichier de config filez.ini

Je ne suis pas sûr que l'installation manuelle d'uploadprogress y soit pour quelque chose, à mon avis le problème venait du fait qu'apache ne fonctionnait pas en mode mod_php, ce qui est un pré-requis au fonctionnement d'uploadprogress.

J'espère que ceci pourra vous aider.
